# final_multimodal_inference.py

from __future__ import annotations

import argparse
import json
import statistics
from pathlib import Path
from typing import Any

import joblib
import librosa
import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from PIL import Image
from sentence_transformers import SentenceTransformer
from transformers import (
    Wav2Vec2FeatureExtractor,
    WavLMModel,
    CLIPModel,
    CLIPProcessor,
)


torch.set_num_threads(2)

FUSION_MODEL_PATH = Path("models/fusion_demo/fusion_pipeline.joblib")
FUSION_FEATURE_COLUMNS_PATH = Path("models/fusion_demo/feature_columns.json")

TEXT_MODEL_PATH = "models/all-mpnet-base-v2"
WAVLM_MODEL_PATH = "models/wavlm-base-plus"
CLIP_MODEL_PATH = "models/clip-vit-large-patch14"

TARGET_SR = 16000
MAX_AUDIO_SECONDS = 20


def get_device() -> torch.device:
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")


def confidence_level(gap: float) -> str:
    if gap >= 0.35:
        return "High"
    if gap >= 0.15:
        return "Medium"
    return "Low"


def safe_mean(values: list[float]) -> float:
    return statistics.mean(values) if values else 0.0


def safe_std(values: list[float]) -> float:
    return statistics.stdev(values) if len(values) >= 2 else 0.0


class FinalMultimodalInference:
    def __init__(self):
        if not FUSION_MODEL_PATH.exists():
            raise FileNotFoundError(f"Fusion model not found: {FUSION_MODEL_PATH}")

        if not FUSION_FEATURE_COLUMNS_PATH.exists():
            raise FileNotFoundError(
                f"Fusion feature schema not found: {FUSION_FEATURE_COLUMNS_PATH}"
            )

        self.device = get_device()
        self.fusion_model = joblib.load(FUSION_MODEL_PATH)

        with open(FUSION_FEATURE_COLUMNS_PATH, "r", encoding="utf-8") as f:
            self.feature_columns = json.load(f)

        self.text_model = SentenceTransformer(TEXT_MODEL_PATH)

        self.wavlm_extractor = Wav2Vec2FeatureExtractor.from_pretrained(WAVLM_MODEL_PATH)
        self.wavlm_model = WavLMModel.from_pretrained(WAVLM_MODEL_PATH).to(self.device)
        self.wavlm_model.eval()

        self.clip_processor = CLIPProcessor.from_pretrained(CLIP_MODEL_PATH)
        self.clip_model = CLIPModel.from_pretrained(CLIP_MODEL_PATH).to(self.device)
        self.clip_model.eval()

    def extract_keystroke_features(self, keystroke_json_path: Path) -> dict[str, Any]:
        with open(keystroke_json_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        if "features" in data:
            return data["features"]

        raise ValueError(
            "Keystroke JSON does not contain a 'features' field. "
            "Use a JSON file generated by the original session collector."
        )

    def extract_text_features(self, text: str) -> dict[str, float]:
        text = text.strip()

        if not text:
            raise ValueError("Text input is empty.")

        embedding = self.text_model.encode(
            [text],
            normalize_embeddings=True,
            show_progress_bar=False,
            convert_to_numpy=True,
        )[0]

        return {
            f"text_mpnet_emb_{i}": float(value)
            for i, value in enumerate(embedding)
        }

    def extract_audio_features(self, audio_path: Path) -> dict[str, float]:
        waveform, sr = librosa.load(audio_path, sr=TARGET_SR, mono=True)
        waveform = waveform.astype(np.float32)

        if len(waveform) == 0:
            raise ValueError(f"Empty audio file: {audio_path}")

        waveform = waveform[: TARGET_SR * MAX_AUDIO_SECONDS]

        duration = librosa.get_duration(y=waveform, sr=sr)

        rms = librosa.feature.rms(y=waveform)[0]
        zcr = librosa.feature.zero_crossing_rate(waveform)[0]
        mfcc = librosa.feature.mfcc(y=waveform, sr=sr, n_mfcc=13)

        spectral_centroid = librosa.feature.spectral_centroid(y=waveform, sr=sr)[0]
        spectral_bandwidth = librosa.feature.spectral_bandwidth(y=waveform, sr=sr)[0]
        spectral_rolloff = librosa.feature.spectral_rolloff(y=waveform, sr=sr)[0]

        pitches, magnitudes = librosa.piptrack(y=waveform, sr=sr)
        threshold = np.median(magnitudes[magnitudes > 0]) if np.any(magnitudes > 0) else 0

        pitch_values = pitches[magnitudes > threshold]
        pitch_values = pitch_values[pitch_values > 0]

        features = {
            "audio_duration": float(duration),
            "audio_rms_mean": float(np.mean(rms)),
            "audio_rms_std": float(np.std(rms)),
            "audio_zcr_mean": float(np.mean(zcr)),
            "audio_zcr_std": float(np.std(zcr)),
            "audio_spectral_centroid_mean": float(np.mean(spectral_centroid)),
            "audio_spectral_centroid_std": float(np.std(spectral_centroid)),
            "audio_spectral_bandwidth_mean": float(np.mean(spectral_bandwidth)),
            "audio_spectral_bandwidth_std": float(np.std(spectral_bandwidth)),
            "audio_spectral_rolloff_mean": float(np.mean(spectral_rolloff)),
            "audio_spectral_rolloff_std": float(np.std(spectral_rolloff)),
            "audio_pitch_mean": float(np.mean(pitch_values)) if len(pitch_values) else 0.0,
            "audio_pitch_std": float(np.std(pitch_values)) if len(pitch_values) else 0.0,
            "audio_pitch_min": float(np.min(pitch_values)) if len(pitch_values) else 0.0,
            "audio_pitch_max": float(np.max(pitch_values)) if len(pitch_values) else 0.0,
        }

        for i in range(13):
            features[f"audio_mfcc_{i}_mean"] = float(np.mean(mfcc[i]))
            features[f"audio_mfcc_{i}_std"] = float(np.std(mfcc[i]))

        inputs = self.wavlm_extractor(
            waveform,
            sampling_rate=TARGET_SR,
            return_tensors="pt",
            padding=True,
        )

        inputs = {key: value.to(self.device) for key, value in inputs.items()}

        with torch.inference_mode():
            outputs = self.wavlm_model(**inputs)

        embedding = outputs.last_hidden_state.mean(dim=1).squeeze(0)
        embedding = F.normalize(embedding, p=2, dim=0)
        embedding = embedding.cpu().numpy()

        for i, value in enumerate(embedding):
            features[f"audio_wavlm_emb_{i}"] = float(value)

        return {
            key: float(value) if np.isfinite(value) else 0.0
            for key, value in features.items()
        }

    def extract_image_features(self, image_path: Path) -> dict[str, float]:
        image = Image.open(image_path).convert("RGB")

        inputs = self.clip_processor(images=image, return_tensors="pt")
        pixel_values = inputs["pixel_values"].to(self.device)

        with torch.no_grad():
            try:
                output = self.clip_model.get_image_features(pixel_values=pixel_values)

                if isinstance(output, torch.Tensor):
                    image_features = output
                elif hasattr(output, "image_embeds"):
                    image_features = output.image_embeds
                elif hasattr(output, "pooler_output"):
                    image_features = output.pooler_output
                elif hasattr(output, "last_hidden_state"):
                    image_features = output.last_hidden_state.mean(dim=1)
                else:
                    raise TypeError(f"Unsupported CLIP output type: {type(output)}")

            except Exception:
                output = self.clip_model.vision_model(pixel_values=pixel_values)

                if hasattr(output, "pooler_output"):
                    image_features = output.pooler_output
                elif hasattr(output, "last_hidden_state"):
                    image_features = output.last_hidden_state.mean(dim=1)
                else:
                    raise TypeError(f"Unsupported CLIP vision output type: {type(output)}")

        image_features = F.normalize(image_features, p=2, dim=-1)
        embedding = image_features.squeeze(0).cpu().numpy()

        return {
            f"image_clip_emb_{i}": float(value)
            for i, value in enumerate(embedding)
        }

    def predict(
        self,
        keystroke_json: Path,
        text: str,
        audio_path: Path,
        image_path: Path,
    ) -> dict[str, Any]:
        features: dict[str, Any] = {}

        features.update(self.extract_keystroke_features(keystroke_json))
        features.update(self.extract_text_features(text))
        features.update(self.extract_audio_features(audio_path))
        features.update(self.extract_image_features(image_path))

        missing = [col for col in self.feature_columns if col not in features]

        if missing:
            raise ValueError(
                "Fusion feature mismatch.\n"
                f"Missing columns: {missing[:30]}"
            )

        x = pd.DataFrame(
            [[features[col] for col in self.feature_columns]],
            columns=self.feature_columns,
        )

        prediction = self.fusion_model.predict(x)[0]
        probabilities = self.fusion_model.predict_proba(x)[0]
        classes = self.fusion_model.classes_

        probability_dict = {
            str(cls): float(prob)
            for cls, prob in zip(classes, probabilities)
        }

        sorted_probs = sorted(
            probability_dict.items(),
            key=lambda item: item[1],
            reverse=True,
        )

        current_state, confidence = sorted_probs[0]
        second_class, second_probability = sorted_probs[1]
        gap = confidence - second_probability

        return {
            "prediction": str(prediction),
            "current_state": current_state,
            "confidence": confidence,
            "confidence_percent": round(confidence * 100, 2),
            "confidence_level": confidence_level(gap),
            "probabilities": probability_dict,
            "technical_details": {
                "top_class": current_state,
                "second_class": second_class,
                "second_probability": second_probability,
                "confidence_gap": gap,
                "feature_dimension": int(x.shape[1]),
                "device": str(self.device),
            },
            "top_class": current_state,
            "top_probability": confidence,
            "second_class": second_class,
            "second_probability": second_probability,
            "confidence_gap": gap,
            "feature_dimension": int(x.shape[1]),
            "device": str(self.device),
        }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Final multimodal behavioural-state inference pipeline."
    )

    parser.add_argument("--keystroke_json", required=True, type=Path)
    parser.add_argument("--text", required=True, type=str)
    parser.add_argument("--audio", required=True, type=Path)
    parser.add_argument("--image", required=True, type=Path)
    parser.add_argument("--output", default=None, type=Path)

    args = parser.parse_args()

    inference = FinalMultimodalInference()

    result = inference.predict(
        keystroke_json=args.keystroke_json,
        text=args.text,
        audio_path=args.audio,
        image_path=args.image,
    )

    output_json = json.dumps(result, indent=4)
    print(output_json)

    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(output_json, encoding="utf-8")


if __name__ == "__main__":
    main()
