# === final_multimodal_inference.py ===
#
# SenseFuzeAI
# Final Session-Aligned Multimodal Behavioural-State Inference Pipeline
#
# =============================================================================
# PURPOSE
# =============================================================================
#
# Runtime inference pipeline corresponding to:
#
#     train_fusion_demo_pipeline.py
#
# Modalities:
#
#     1. Keystroke dynamics
#     2. MPNet text embeddings
#     3. Librosa + WavLM audio features
#     4. CLIP image embeddings
#     5. Webcam-calibrated image probabilities
#
# IMPORTANT
# =============================================================================
#
# The final fusion model may now expect six additional image-derived features:
#
#     image_webcam_focused_prob
#     image_webcam_distracted_prob
#     image_webcam_fatigued_prob
#     image_webcam_overloaded_prob
#     image_webcam_top_probability
#     image_webcam_confidence_gap
#
# These features are generated by applying:
#
#     models/image_demo/image_pipeline_webcam_calibrated.joblib
#
# to the SAME 768-dimensional CLIP embedding extracted from the current image
# or webcam frame.
#
# The original image model remains untouched.
#
# =============================================================================

from __future__ import annotations

import argparse
import json
import statistics
from pathlib import Path
from typing import Any

import joblib
import librosa
import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from PIL import Image
from sentence_transformers import SentenceTransformer
from transformers import (
    CLIPModel,
    CLIPProcessor,
    Wav2Vec2FeatureExtractor,
    WavLMModel,
)


# =============================================================================
# TORCH CONFIGURATION
# =============================================================================

torch.set_num_threads(2)


# =============================================================================
# PROJECT PATHS
# =============================================================================

ROOT_DIR = Path(__file__).resolve().parent


# =============================================================================
# FUSION MODEL
# =============================================================================

FUSION_MODEL_PATH = (
    ROOT_DIR
    / "models"
    / "fusion_demo"
    / "fusion_pipeline.joblib"
)

FUSION_FEATURE_COLUMNS_PATH = (
    ROOT_DIR
    / "models"
    / "fusion_demo"
    / "feature_columns.json"
)


# =============================================================================
# PRETRAINED MODELS
# =============================================================================

TEXT_MODEL_PATH = (
    ROOT_DIR
    / "models"
    / "all-mpnet-base-v2"
)

WAVLM_MODEL_PATH = (
    ROOT_DIR
    / "models"
    / "wavlm-base-plus"
)

CLIP_MODEL_PATH = (
    ROOT_DIR
    / "models"
    / "clip-vit-large-patch14"
)


# =============================================================================
# WEBCAM-CALIBRATED IMAGE MODEL
# =============================================================================

WEBCAM_IMAGE_MODEL_PATH = (
    ROOT_DIR
    / "models"
    / "image_demo"
    / "image_pipeline_webcam_calibrated.joblib"
)

WEBCAM_IMAGE_FEATURE_COLUMNS_PATH = (
    ROOT_DIR
    / "models"
    / "image_demo"
    / "feature_columns.json"
)

WEBCAM_IMAGE_METADATA_PATH = (
    ROOT_DIR
    / "models"
    / "image_demo"
    / "webcam_calibrated_metadata.json"
)


# =============================================================================
# CONFIGURATION
# =============================================================================

TARGET_SR = 16000
MAX_AUDIO_SECONDS = 20

CLASSES = [
    "focused",
    "distracted",
    "fatigued",
    "overloaded",
]

WEBCAM_PROBABILITY_COLUMNS = [
    "image_webcam_focused_prob",
    "image_webcam_distracted_prob",
    "image_webcam_fatigued_prob",
    "image_webcam_overloaded_prob",
]

WEBCAM_CONFIDENCE_COLUMNS = [
    "image_webcam_top_probability",
    "image_webcam_confidence_gap",
]


# =============================================================================
# GENERAL UTILITIES
# =============================================================================

def get_device() -> torch.device:
    return torch.device(
        "cuda"
        if torch.cuda.is_available()
        else "cpu"
    )


def confidence_level(
    gap: float,
) -> str:
    if gap >= 0.35:
        return "High"

    if gap >= 0.15:
        return "Medium"

    return "Low"


def safe_mean(
    values: list[float],
) -> float:
    return (
        statistics.mean(values)
        if values
        else 0.0
    )


def safe_std(
    values: list[float],
) -> float:
    return (
        statistics.stdev(values)
        if len(values) >= 2
        else 0.0
    )


def normalise_label(
    value: Any,
) -> str:
    if value is None:
        return ""

    return (
        str(value)
        .strip()
        .lower()
    )


def clean_float(
    value: Any,
) -> float:
    """
    Convert a value to finite float.
    """

    try:
        numeric = float(value)

        if np.isfinite(numeric):
            return numeric

    except Exception:
        pass

    return 0.0


def load_json_list(
    path: Path,
) -> list[str]:
    if not path.exists():
        return []

    try:
        with path.open(
            "r",
            encoding="utf-8",
        ) as f:
            value = json.load(f)

        if not isinstance(
            value,
            list,
        ):
            return []

        return [
            str(item)
            for item
            in value
        ]

    except Exception:
        return []


def get_model_classes(
    model: Any,
) -> list[str]:
    """
    Obtain class ordering from either a classifier or sklearn Pipeline.
    """

    classes = getattr(
        model,
        "classes_",
        None,
    )

    if classes is not None:
        return [
            normalise_label(label)
            for label
            in classes
        ]

    if hasattr(
        model,
        "named_steps",
    ):
        for step in reversed(
            list(
                model.named_steps.values()
            )
        ):
            classes = getattr(
                step,
                "classes_",
                None,
            )

            if classes is not None:
                return [
                    normalise_label(label)
                    for label
                    in classes
                ]

    return []


def softmax(
    values: np.ndarray,
) -> np.ndarray:
    values = np.asarray(
        values,
        dtype=float,
    )

    values = (
        values
        - np.max(values)
    )

    exp_values = np.exp(
        values
    )

    total = float(
        np.sum(exp_values)
    )

    if total <= 0:
        return (
            np.ones_like(exp_values)
            / len(exp_values)
        )

    return exp_values / total


# =============================================================================
# FINAL MULTIMODAL INFERENCE
# =============================================================================

class FinalMultimodalInference:

    def __init__(self) -> None:

        # ---------------------------------------------------------------------
        # Validate fusion artifacts
        # ---------------------------------------------------------------------

        if not FUSION_MODEL_PATH.exists():
            raise FileNotFoundError(
                f"Fusion model not found:\n"
                f"{FUSION_MODEL_PATH}"
            )

        if not FUSION_FEATURE_COLUMNS_PATH.exists():
            raise FileNotFoundError(
                f"Fusion feature schema not found:\n"
                f"{FUSION_FEATURE_COLUMNS_PATH}"
            )

        if not TEXT_MODEL_PATH.exists():
            raise FileNotFoundError(
                f"MPNet model not found:\n"
                f"{TEXT_MODEL_PATH}"
            )

        if not WAVLM_MODEL_PATH.exists():
            raise FileNotFoundError(
                f"WavLM model not found:\n"
                f"{WAVLM_MODEL_PATH}"
            )

        if not CLIP_MODEL_PATH.exists():
            raise FileNotFoundError(
                f"CLIP model not found:\n"
                f"{CLIP_MODEL_PATH}"
            )

        # ---------------------------------------------------------------------
        # Device
        # ---------------------------------------------------------------------

        self.device = get_device()

        # ---------------------------------------------------------------------
        # Fusion classifier
        # ---------------------------------------------------------------------

        self.fusion_model = joblib.load(
            FUSION_MODEL_PATH
        )

        with FUSION_FEATURE_COLUMNS_PATH.open(
            "r",
            encoding="utf-8",
        ) as f:
            self.feature_columns = json.load(f)

        if not isinstance(
            self.feature_columns,
            list,
        ):
            raise ValueError(
                "Fusion feature_columns.json must contain a JSON list."
            )

        # ---------------------------------------------------------------------
        # Text model
        # ---------------------------------------------------------------------

        self.text_model = SentenceTransformer(
            str(TEXT_MODEL_PATH)
        )

        # ---------------------------------------------------------------------
        # Audio model
        # ---------------------------------------------------------------------

        self.wavlm_extractor = (
            Wav2Vec2FeatureExtractor
            .from_pretrained(
                str(WAVLM_MODEL_PATH)
            )
        )

        self.wavlm_model = (
            WavLMModel
            .from_pretrained(
                str(WAVLM_MODEL_PATH)
            )
            .to(
                self.device
            )
        )

        self.wavlm_model.eval()

        # ---------------------------------------------------------------------
        # CLIP image model
        # ---------------------------------------------------------------------

        self.clip_processor = (
            CLIPProcessor
            .from_pretrained(
                str(CLIP_MODEL_PATH)
            )
        )

        self.clip_model = (
            CLIPModel
            .from_pretrained(
                str(CLIP_MODEL_PATH)
            )
            .to(
                self.device
            )
        )

        self.clip_model.eval()

        # ---------------------------------------------------------------------
        # Webcam-calibrated classifier
        # ---------------------------------------------------------------------

        self.webcam_image_model = None
        self.webcam_image_feature_columns: list[str] = []

        self._load_webcam_calibration_model()

        # ---------------------------------------------------------------------
        # Validate runtime/fusion compatibility
        # ---------------------------------------------------------------------

        self._validate_runtime_schema()


    # =========================================================================
    # INITIALISATION HELPERS
    # =========================================================================

    def _load_webcam_calibration_model(
        self,
    ) -> None:
        """
        Load the separately preserved webcam-calibrated image classifier.

        It is required only if the current fusion feature schema contains
        image_webcam_* features.
        """

        webcam_features_required = any(
            column.startswith(
                "image_webcam_"
            )
            for column
            in self.feature_columns
        )

        if not webcam_features_required:
            return

        if not WEBCAM_IMAGE_MODEL_PATH.exists():
            raise FileNotFoundError(
                "The fusion model expects webcam-calibrated image features, "
                "but the calibrated image classifier is missing:\n"
                f"{WEBCAM_IMAGE_MODEL_PATH}"
            )

        if not WEBCAM_IMAGE_FEATURE_COLUMNS_PATH.exists():
            raise FileNotFoundError(
                "The fusion model expects webcam-calibrated image features, "
                "but the calibrated image feature schema is missing:\n"
                f"{WEBCAM_IMAGE_FEATURE_COLUMNS_PATH}"
            )

        self.webcam_image_feature_columns = load_json_list(
            WEBCAM_IMAGE_FEATURE_COLUMNS_PATH
        )

        if not self.webcam_image_feature_columns:
            raise ValueError(
                "Webcam calibrated image feature schema is empty."
            )

        self.webcam_image_model = joblib.load(
            WEBCAM_IMAGE_MODEL_PATH
        )


    def _validate_runtime_schema(
        self,
    ) -> None:
        """
        Validate major runtime assumptions before accepting predictions.
        """

        webcam_required_columns = {
            *WEBCAM_PROBABILITY_COLUMNS,
            *WEBCAM_CONFIDENCE_COLUMNS,
        }

        fusion_webcam_columns = {
            column
            for column
            in self.feature_columns
            if column.startswith(
                "image_webcam_"
            )
        }

        if fusion_webcam_columns:
            missing = (
                fusion_webcam_columns
                - webcam_required_columns
            )

            if missing:
                raise ValueError(
                    "Fusion schema contains unsupported webcam image "
                    f"features: {sorted(missing)}"
                )

        clip_columns = [
            column
            for column
            in self.feature_columns
            if column.startswith(
                "image_clip_emb_"
            )
        ]

        if clip_columns:
            max_index = max(
                int(
                    column.rsplit(
                        "_",
                        1,
                    )[1]
                )
                for column
                in clip_columns
            )

            expected_dimension = (
                max_index + 1
            )

            print(
                "Fusion image embedding dimension expected:",
                expected_dimension,
            )

        print(
            "FinalMultimodalInference initialised successfully."
        )

        print(
            f"Device: {self.device}"
        )

        print(
            f"Fusion features: {len(self.feature_columns)}"
        )

        print(
            "Webcam-calibrated image augmentation:",
            (
                "enabled"
                if self.webcam_image_model is not None
                else "not required"
            ),
        )


    # =========================================================================
    # KEYSTROKE FEATURES
    # =========================================================================

    def extract_keystroke_features(
        self,
        keystroke_json_path: Path,
    ) -> dict[str, Any]:
        """
        Load already-extracted keystroke features from a session JSON.

        Both original and keystroke_-prefixed aliases are returned so this
        runtime remains compatible with the updated fusion training schema.
        """

        keystroke_json_path = Path(
            keystroke_json_path
        )

        if not keystroke_json_path.exists():
            raise FileNotFoundError(
                f"Keystroke JSON not found:\n"
                f"{keystroke_json_path}"
            )

        with keystroke_json_path.open(
            "r",
            encoding="utf-8",
        ) as f:
            data = json.load(f)

        if (
            not isinstance(data, dict)
            or "features" not in data
        ):
            raise ValueError(
                "Keystroke JSON does not contain a 'features' field. "
                "Use a JSON file generated by the session collector."
            )

        raw_features = data[
            "features"
        ]

        if not isinstance(
            raw_features,
            dict,
        ):
            raise ValueError(
                "Keystroke 'features' must be a JSON object."
            )

        output: dict[
            str,
            float,
        ] = {}

        for key, value in raw_features.items():
            clean_value = clean_float(
                value
            )

            # Preserve original feature.
            output[
                str(key)
            ] = clean_value

            # Also expose the schema used by train_fusion_demo_pipeline.py.
            if str(key).startswith(
                "keystroke_"
            ):
                output[
                    str(key)
                ] = clean_value

            else:
                output[
                    f"keystroke_{key}"
                ] = clean_value

        return output


    # =========================================================================
    # TEXT FEATURES
    # =========================================================================

    def extract_text_features(
        self,
        text: str,
    ) -> dict[str, float]:

        text = (
            text
            .strip()
        )

        if not text:
            raise ValueError(
                "Text input is empty."
            )

        embedding = self.text_model.encode(
            [text],
            normalize_embeddings=True,
            show_progress_bar=False,
            convert_to_numpy=True,
        )[0]

        features = {
            f"text_mpnet_emb_{index}":
            clean_float(value)

            for index, value
            in enumerate(
                embedding
            )
        }

        return features


    # =========================================================================
    # AUDIO FEATURES
    # =========================================================================

    def extract_audio_features(
        self,
        audio_path: Path,
    ) -> dict[str, float]:

        audio_path = Path(
            audio_path
        )

        if not audio_path.exists():
            raise FileNotFoundError(
                f"Audio file not found:\n"
                f"{audio_path}"
            )

        waveform, sr = librosa.load(
            audio_path,
            sr=TARGET_SR,
            mono=True,
        )

        waveform = waveform.astype(
            np.float32
        )

        if len(
            waveform
        ) == 0:
            raise ValueError(
                f"Empty audio file:\n"
                f"{audio_path}"
            )

        # Maximum duration must match the training feature extractor.
        waveform = waveform[
            : TARGET_SR
            * MAX_AUDIO_SECONDS
        ]

        duration = librosa.get_duration(
            y=waveform,
            sr=sr,
        )

        # ---------------------------------------------------------------------
        # Classical acoustic features
        # ---------------------------------------------------------------------

        rms = librosa.feature.rms(
            y=waveform
        )[0]

        zcr = librosa.feature.zero_crossing_rate(
            waveform
        )[0]

        mfcc = librosa.feature.mfcc(
            y=waveform,
            sr=sr,
            n_mfcc=13,
        )

        spectral_centroid = (
            librosa.feature
            .spectral_centroid(
                y=waveform,
                sr=sr,
            )[0]
        )

        spectral_bandwidth = (
            librosa.feature
            .spectral_bandwidth(
                y=waveform,
                sr=sr,
            )[0]
        )

        spectral_rolloff = (
            librosa.feature
            .spectral_rolloff(
                y=waveform,
                sr=sr,
            )[0]
        )

        pitches, magnitudes = (
            librosa.piptrack(
                y=waveform,
                sr=sr,
            )
        )

        if np.any(
            magnitudes > 0
        ):
            threshold = np.median(
                magnitudes[
                    magnitudes > 0
                ]
            )

        else:
            threshold = 0.0

        pitch_values = pitches[
            magnitudes > threshold
        ]

        pitch_values = pitch_values[
            pitch_values > 0
        ]

        features: dict[
            str,
            float,
        ] = {
            "audio_duration":
                clean_float(duration),

            "audio_rms_mean":
                clean_float(
                    np.mean(rms)
                ),

            "audio_rms_std":
                clean_float(
                    np.std(rms)
                ),

            "audio_zcr_mean":
                clean_float(
                    np.mean(zcr)
                ),

            "audio_zcr_std":
                clean_float(
                    np.std(zcr)
                ),

            "audio_spectral_centroid_mean":
                clean_float(
                    np.mean(
                        spectral_centroid
                    )
                ),

            "audio_spectral_centroid_std":
                clean_float(
                    np.std(
                        spectral_centroid
                    )
                ),

            "audio_spectral_bandwidth_mean":
                clean_float(
                    np.mean(
                        spectral_bandwidth
                    )
                ),

            "audio_spectral_bandwidth_std":
                clean_float(
                    np.std(
                        spectral_bandwidth
                    )
                ),

            "audio_spectral_rolloff_mean":
                clean_float(
                    np.mean(
                        spectral_rolloff
                    )
                ),

            "audio_spectral_rolloff_std":
                clean_float(
                    np.std(
                        spectral_rolloff
                    )
                ),

            "audio_pitch_mean":
                clean_float(
                    np.mean(
                        pitch_values
                    )
                )
                if len(
                    pitch_values
                )
                else 0.0,

            "audio_pitch_std":
                clean_float(
                    np.std(
                        pitch_values
                    )
                )
                if len(
                    pitch_values
                )
                else 0.0,

            "audio_pitch_min":
                clean_float(
                    np.min(
                        pitch_values
                    )
                )
                if len(
                    pitch_values
                )
                else 0.0,

            "audio_pitch_max":
                clean_float(
                    np.max(
                        pitch_values
                    )
                )
                if len(
                    pitch_values
                )
                else 0.0,
        }

        # ---------------------------------------------------------------------
        # MFCC
        # ---------------------------------------------------------------------

        for index in range(
            13
        ):
            features[
                f"audio_mfcc_{index}_mean"
            ] = clean_float(
                np.mean(
                    mfcc[
                        index
                    ]
                )
            )

            features[
                f"audio_mfcc_{index}_std"
            ] = clean_float(
                np.std(
                    mfcc[
                        index
                    ]
                )
            )

        # ---------------------------------------------------------------------
        # WavLM embedding
        # ---------------------------------------------------------------------

        inputs = self.wavlm_extractor(
            waveform,
            sampling_rate=TARGET_SR,
            return_tensors="pt",
            padding=True,
        )

        inputs = {
            key: value.to(
                self.device
            )
            for key, value
            in inputs.items()
        }

        with torch.inference_mode():
            outputs = self.wavlm_model(
                **inputs
            )

        embedding = (
            outputs
            .last_hidden_state
            .mean(
                dim=1
            )
            .squeeze(0)
        )

        embedding = F.normalize(
            embedding,
            p=2,
            dim=0,
        )

        embedding = (
            embedding
            .detach()
            .cpu()
            .numpy()
        )

        for index, value in enumerate(
            embedding
        ):
            features[
                f"audio_wavlm_emb_{index}"
            ] = clean_float(
                value
            )

        return features


    # =========================================================================
    # RAW CLIP EMBEDDING
    # =========================================================================

    def extract_clip_embedding(
        self,
        image: Image.Image,
    ) -> np.ndarray:
        """
        Extract exactly one normalized CLIP visual embedding.

        Both the fusion image feature branch and webcam-calibrated classifier
        use this SAME embedding.
        """

        image = image.convert(
            "RGB"
        )

        inputs = self.clip_processor(
            images=image,
            return_tensors="pt",
        )

        pixel_values = (
            inputs[
                "pixel_values"
            ]
            .to(
                self.device
            )
        )

        with torch.inference_mode():

            try:
                output = (
                    self.clip_model
                    .get_image_features(
                        pixel_values=pixel_values
                    )
                )

                if isinstance(
                    output,
                    torch.Tensor,
                ):
                    image_features = (
                        output
                    )

                elif hasattr(
                    output,
                    "image_embeds",
                ):
                    image_features = (
                        output.image_embeds
                    )

                elif hasattr(
                    output,
                    "pooler_output",
                ):
                    image_features = (
                        output.pooler_output
                    )

                elif hasattr(
                    output,
                    "last_hidden_state",
                ):
                    image_features = (
                        output
                        .last_hidden_state
                        .mean(
                            dim=1
                        )
                    )

                else:
                    raise TypeError(
                        "Unsupported CLIP output type: "
                        f"{type(output)}"
                    )

            except Exception:
                vision_output = (
                    self.clip_model
                    .vision_model(
                        pixel_values=pixel_values
                    )
                )

                if hasattr(
                    vision_output,
                    "pooler_output",
                ):
                    image_features = (
                        vision_output
                        .pooler_output
                    )

                elif hasattr(
                    vision_output,
                    "last_hidden_state",
                ):
                    image_features = (
                        vision_output
                        .last_hidden_state
                        .mean(
                            dim=1
                        )
                    )

                else:
                    raise TypeError(
                        "Unsupported CLIP vision output type: "
                        f"{type(vision_output)}"
                    )

        image_features = F.normalize(
            image_features,
            p=2,
            dim=-1,
        )

        embedding = (
            image_features
            .squeeze(0)
            .detach()
            .cpu()
            .numpy()
        )

        return np.asarray(
            embedding,
            dtype=np.float32,
        )


    # =========================================================================
    # WEBCAM-CALIBRATED IMAGE CLASSIFIER
    # =========================================================================

    def extract_webcam_calibration_features(
        self,
        clip_features: dict[str, float],
    ) -> dict[str, float]:
        """
        Convert current-frame CLIP features into the six calibrated image
        features used during fusion training.
        """

        if self.webcam_image_model is None:
            return {}

        if not self.webcam_image_feature_columns:
            raise ValueError(
                "Webcam calibrated image model is loaded, "
                "but its feature schema is missing."
            )

        # ---------------------------------------------------------------------
        # Verify all required CLIP dimensions exist
        # ---------------------------------------------------------------------

        missing = [
            column
            for column
            in self.webcam_image_feature_columns
            if column not in clip_features
        ]

        if missing:
            raise ValueError(
                "Webcam calibrated image feature mismatch.\n"
                f"Missing CLIP columns: {missing[:20]}"
            )

        # ---------------------------------------------------------------------
        # Build calibrated classifier input
        # ---------------------------------------------------------------------

        row = {
            column: clean_float(
                clip_features[
                    column
                ]
            )
            for column
            in self.webcam_image_feature_columns
        }

        X_image = pd.DataFrame(
            [row],
            columns=self.webcam_image_feature_columns,
        )

        model_classes = get_model_classes(
            self.webcam_image_model
        )

        # ---------------------------------------------------------------------
        # Obtain class probabilities
        # ---------------------------------------------------------------------

        probability_lookup = {
            label: 0.0
            for label
            in CLASSES
        }

        if hasattr(
            self.webcam_image_model,
            "predict_proba",
        ):
            probabilities = (
                self.webcam_image_model
                .predict_proba(
                    X_image
                )[0]
            )

            for label, probability in zip(
                model_classes,
                probabilities,
            ):
                if label in CLASSES:
                    probability_lookup[
                        label
                    ] = clean_float(
                        probability
                    )

        elif hasattr(
            self.webcam_image_model,
            "decision_function",
        ):
            scores = np.asarray(
                self.webcam_image_model
                .decision_function(
                    X_image
                )
            )

            if scores.ndim > 1:
                scores = scores[
                    0
                ]

            if scores.ndim == 0:
                scores = np.asarray(
                    [float(scores)]
                )

            probabilities = softmax(
                scores
            )

            for label, probability in zip(
                model_classes,
                probabilities,
            ):
                if label in CLASSES:
                    probability_lookup[
                        label
                    ] = clean_float(
                        probability
                    )

        else:
            predicted_class = normalise_label(
                self.webcam_image_model
                .predict(
                    X_image
                )[0]
            )

            if predicted_class in CLASSES:
                probability_lookup[
                    predicted_class
                ] = 1.0

        # ---------------------------------------------------------------------
        # Normalise probability vector defensively
        # ---------------------------------------------------------------------

        probability_values = np.asarray(
            [
                probability_lookup[
                    label
                ]
                for label
                in CLASSES
            ],
            dtype=float,
        )

        total = float(
            np.sum(
                probability_values
            )
        )

        if total > 0:
            probability_values = (
                probability_values
                / total
            )

        else:
            probability_values = np.full(
                len(CLASSES),
                1.0 / len(CLASSES),
                dtype=float,
            )

        probability_lookup = {
            label: float(
                probability
            )
            for label, probability
            in zip(
                CLASSES,
                probability_values,
            )
        }

        ranked = sorted(
            probability_lookup.items(),
            key=lambda item: item[1],
            reverse=True,
        )

        top_probability = (
            ranked[0][1]
        )

        second_probability = (
            ranked[1][1]
            if len(ranked) > 1
            else 0.0
        )

        confidence_gap = (
            top_probability
            - second_probability
        )

        # ---------------------------------------------------------------------
        # EXACT six features expected by the fusion training pipeline
        # ---------------------------------------------------------------------

        return {
            "image_webcam_focused_prob":
                probability_lookup[
                    "focused"
                ],

            "image_webcam_distracted_prob":
                probability_lookup[
                    "distracted"
                ],

            "image_webcam_fatigued_prob":
                probability_lookup[
                    "fatigued"
                ],

            "image_webcam_overloaded_prob":
                probability_lookup[
                    "overloaded"
                ],

            "image_webcam_top_probability":
                float(
                    top_probability
                ),

            "image_webcam_confidence_gap":
                float(
                    confidence_gap
                ),
        }


    # =========================================================================
    # COMPLETE IMAGE FEATURES
    # =========================================================================

    def extract_image_features(
        self,
        image_path: Path,
    ) -> dict[str, float]:
        """
        Extract both:

            image_clip_emb_*
            image_webcam_* calibrated probabilities/confidence

        from one image/frame.
        """

        image_path = Path(
            image_path
        )

        if not image_path.exists():
            raise FileNotFoundError(
                f"Image file not found:\n"
                f"{image_path}"
            )

        with Image.open(
            image_path
        ) as image_file:
            image = image_file.convert(
                "RGB"
            )

            embedding = self.extract_clip_embedding(
                image
            )

        clip_features = {
            f"image_clip_emb_{index}":
            clean_float(value)

            for index, value
            in enumerate(
                embedding
            )
        }

        calibrated_features = (
            self.extract_webcam_calibration_features(
                clip_features
            )
        )

        return {
            **clip_features,
            **calibrated_features,
        }


    # =========================================================================
    # FEATURE VECTOR VALIDATION
    # =========================================================================

    def build_fusion_dataframe(
        self,
        features: dict[str, Any],
    ) -> pd.DataFrame:
        """
        Build a fusion input row in EXACTLY the saved training feature order.
        """

        missing = [
            column
            for column
            in self.feature_columns
            if column not in features
        ]

        if missing:
            raise ValueError(
                "Fusion feature mismatch.\n\n"
                f"Expected feature count: {len(self.feature_columns)}\n"
                f"Available runtime features: {len(features)}\n"
                f"Missing feature count: {len(missing)}\n"
                f"Missing examples: {missing[:30]}"
            )

        row = {
            column: clean_float(
                features[
                    column
                ]
            )
            for column
            in self.feature_columns
        }

        return pd.DataFrame(
            [row],
            columns=self.feature_columns,
        )


    # =========================================================================
    # FUSION PREDICTION
    # =========================================================================

    def predict(
        self,
        keystroke_json: Path,
        text: str,
        audio_path: Path,
        image_path: Path,
    ) -> dict[str, Any]:

        features: dict[
            str,
            Any,
        ] = {}

        # ---------------------------------------------------------------------
        # Extract all modalities
        # ---------------------------------------------------------------------

        keystroke_features = (
            self.extract_keystroke_features(
                keystroke_json
            )
        )

        text_features = (
            self.extract_text_features(
                text
            )
        )

        audio_features = (
            self.extract_audio_features(
                audio_path
            )
        )

        image_features = (
            self.extract_image_features(
                image_path
            )
        )

        features.update(
            keystroke_features
        )

        features.update(
            text_features
        )

        features.update(
            audio_features
        )

        features.update(
            image_features
        )

        # ---------------------------------------------------------------------
        # Exact fusion vector
        # ---------------------------------------------------------------------

        X = self.build_fusion_dataframe(
            features
        )

        # ---------------------------------------------------------------------
        # Prediction
        # ---------------------------------------------------------------------

        prediction = (
            self.fusion_model
            .predict(
                X
            )[0]
        )

        probability_dict: dict[
            str,
            float,
        ]

        if hasattr(
            self.fusion_model,
            "predict_proba",
        ):
            probabilities = (
                self.fusion_model
                .predict_proba(
                    X
                )[0]
            )

            classes = get_model_classes(
                self.fusion_model
            )

            if not classes:
                classes = [
                    normalise_label(
                        item
                    )
                    for item
                    in self.fusion_model.classes_
                ]

            probability_dict = {
                normalise_label(
                    class_name
                ):
                clean_float(
                    probability
                )

                for class_name, probability
                in zip(
                    classes,
                    probabilities,
                )
            }

        elif hasattr(
            self.fusion_model,
            "decision_function",
        ):
            scores = np.asarray(
                self.fusion_model
                .decision_function(
                    X
                )
            )

            if scores.ndim > 1:
                scores = scores[
                    0
                ]

            probabilities = softmax(
                scores
            )

            classes = get_model_classes(
                self.fusion_model
            )

            probability_dict = {
                normalise_label(
                    class_name
                ):
                clean_float(
                    probability
                )

                for class_name, probability
                in zip(
                    classes,
                    probabilities,
                )
            }

        else:
            predicted_label = normalise_label(
                prediction
            )

            probability_dict = {
                label: (
                    1.0
                    if label
                    == predicted_label
                    else 0.0
                )
                for label
                in CLASSES
            }

        # ---------------------------------------------------------------------
        # Guarantee four behavioural classes in output
        # ---------------------------------------------------------------------

        for label in CLASSES:
            probability_dict.setdefault(
                label,
                0.0,
            )

        ranked = sorted(
            probability_dict.items(),
            key=lambda item: item[1],
            reverse=True,
        )

        current_state = (
            ranked[0][0]
        )

        confidence = float(
            ranked[0][1]
        )

        if len(
            ranked
        ) > 1:
            second_class = (
                ranked[1][0]
            )

            second_probability = float(
                ranked[1][1]
            )

        else:
            second_class = "none"
            second_probability = 0.0

        confidence_gap = (
            confidence
            - second_probability
        )

        # ---------------------------------------------------------------------
        # Webcam-calibration diagnostics
        # ---------------------------------------------------------------------

        webcam_probabilities = {
            label: image_features.get(
                f"image_webcam_{label}_prob"
            )
            for label
            in CLASSES
        }

        webcam_top_probability = (
            image_features.get(
                "image_webcam_top_probability"
            )
        )

        webcam_confidence_gap = (
            image_features.get(
                "image_webcam_confidence_gap"
            )
        )

        webcam_ranked = [
            (
                label,
                probability,
            )
            for label, probability
            in webcam_probabilities.items()
            if probability is not None
        ]

        webcam_ranked.sort(
            key=lambda item: item[1],
            reverse=True,
        )

        webcam_current_state = (
            webcam_ranked[0][0]
            if webcam_ranked
            else None
        )

        # ---------------------------------------------------------------------
        # Result
        # ---------------------------------------------------------------------

        return {
            "prediction": (
                str(
                    prediction
                )
            ),

            "current_state": (
                current_state
            ),

            "confidence": (
                confidence
            ),

            "confidence_percent": round(
                confidence * 100,
                2,
            ),

            "confidence_level": (
                confidence_level(
                    confidence_gap
                )
            ),

            "probabilities": (
                probability_dict
            ),

            "top_class": (
                current_state
            ),

            "top_probability": (
                confidence
            ),

            "second_class": (
                second_class
            ),

            "second_probability": (
                second_probability
            ),

            "confidence_gap": (
                confidence_gap
            ),

            "feature_dimension": int(
                X.shape[1]
            ),

            "device": str(
                self.device
            ),

            "used_modalities": {
                "keystroke": True,
                "text": True,
                "audio": True,
                "image": True,
                "webcam_image_calibration": (
                    self.webcam_image_model
                    is not None
                ),
            },

            "image_calibration": {
                "enabled": (
                    self.webcam_image_model
                    is not None
                ),

                "current_state": (
                    webcam_current_state
                ),

                "probabilities": (
                    webcam_probabilities
                ),

                "top_probability": (
                    webcam_top_probability
                ),

                "confidence_gap": (
                    webcam_confidence_gap
                ),

                "model_path": str(
                    WEBCAM_IMAGE_MODEL_PATH
                ),
            },

            "technical_details": {
                "top_class": (
                    current_state
                ),

                "second_class": (
                    second_class
                ),

                "second_probability": (
                    second_probability
                ),

                "confidence_gap": (
                    confidence_gap
                ),

                "feature_dimension": int(
                    X.shape[1]
                ),

                "device": str(
                    self.device
                ),

                "fusion_model_path": str(
                    FUSION_MODEL_PATH
                ),

                "fusion_schema_path": str(
                    FUSION_FEATURE_COLUMNS_PATH
                ),

                "webcam_calibration_enabled": (
                    self.webcam_image_model
                    is not None
                ),
            },
        }


# =============================================================================
# COMMAND-LINE INTERFACE
# =============================================================================

def main() -> None:

    parser = argparse.ArgumentParser(
        description=(
            "SenseFuzeAI final session-aligned multimodal "
            "behavioural-state inference pipeline."
        )
    )

    parser.add_argument(
        "--keystroke_json",
        required=True,
        type=Path,
        help=(
            "Path to a session keystroke JSON containing "
            "a 'features' object."
        ),
    )

    parser.add_argument(
        "--text",
        required=True,
        type=str,
        help=(
            "Typed text associated with the session."
        ),
    )

    parser.add_argument(
        "--audio",
        required=True,
        type=Path,
        help=(
            "Path to the session audio file."
        ),
    )

    parser.add_argument(
        "--image",
        required=True,
        type=Path,
        help=(
            "Path to the session image or captured webcam frame."
        ),
    )

    parser.add_argument(
        "--output",
        default=None,
        type=Path,
        help=(
            "Optional JSON result output path."
        ),
    )

    args = parser.parse_args()

    inference = FinalMultimodalInference()

    result = inference.predict(
        keystroke_json=args.keystroke_json,
        text=args.text,
        audio_path=args.audio,
        image_path=args.image,
    )

    output_json = json.dumps(
        result,
        indent=4,
    )

    print()
    print(
        "=" * 80
    )

    print(
        "SenseFuzeAI Final Multimodal Prediction"
    )

    print(
        "=" * 80
    )

    print(
        output_json
    )

    if args.output is not None:
        args.output.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        args.output.write_text(
            output_json,
            encoding="utf-8",
        )

        print()
        print(
            f"Prediction saved to:\n"
            f"{args.output}"
        )


# =============================================================================
# ENTRY POINT
# =============================================================================

if __name__ == "__main__":
    main()
