"""
final_multimodal_inference.py

SenseFuzeAI
Canonical Stateless Multimodal Behavioural-State Inference Pipeline

=============================================================================
PURPOSE
=============================================================================

This module performs ONE multimodal inference observation from:

    1. Keystroke dynamics
    2. MPNet text embeddings
    3. Librosa + WavLM audio features
    4. CLIP image embeddings
    5. Optional webcam-calibrated image probabilities

The resulting heterogeneous features are aligned to the exact feature
schema used to train the final fusion classifier.

This module intentionally DOES NOT maintain:

    - temporal probability history
    - rolling aggregation windows
    - temporal probability averaging
    - temporal generation state
    - reset behaviour

Those responsibilities belong exclusively to:

    temporal_fusion.py

Canonical architecture:

    current text
        |
    keystroke JSON
        |
    audio file
        |
    current image/frame
        |
        v
    FinalMultimodalInference.predict(...)
        |
        | ONE canonical raw probability vector
        v
    temporal_fusion.py
        |
        v
    desktop/web temporal result

=============================================================================
OUTPUT CONTRACT
=============================================================================

predict(...) returns exactly one four-class probability distribution:

    focused
    distracted
    fatigued
    overloaded

The probability distribution is:

    - finite
    - non-negative
    - restricted to the canonical four classes
    - normalised to sum to 1.0

The canonical current raw state is the argmax of that probability vector.

=============================================================================
WEBCAM-CALIBRATED IMAGE AUGMENTATION
=============================================================================

The current fusion model may require six additional image-derived features:

    image_webcam_focused_prob
    image_webcam_distracted_prob
    image_webcam_fatigued_prob
    image_webcam_overloaded_prob
    image_webcam_top_probability
    image_webcam_confidence_gap

These are generated by:

    models/image_demo/image_pipeline_webcam_calibrated.joblib

using the SAME CLIP embedding produced for the normal image branch.

The calibrated image model does not replace CLIP. It augments the fusion
feature vector.

=============================================================================
"""

from __future__ import annotations

import argparse
import json
import statistics

from pathlib import Path
from typing import Any

import joblib
import librosa
import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F

from PIL import Image

from sentence_transformers import (
    SentenceTransformer,
)

from transformers import (
    CLIPModel,
    CLIPProcessor,
    Wav2Vec2FeatureExtractor,
    WavLMModel,
)

from temporal_fusion import (
    LABELS,
    PROBABILITY_SUM_TOLERANCE,
    normalise_probability_dict,
    summarise_probability_dict,
    validate_probability_distribution,
)


# =============================================================================
# TORCH CONFIGURATION
# =============================================================================

torch.set_num_threads(
    2
)


# =============================================================================
# PROJECT PATHS
# =============================================================================

ROOT_DIR = (
    Path(__file__)
    .resolve()
    .parent
)


# =============================================================================
# FUSION MODEL
# =============================================================================

FUSION_MODEL_PATH = (
    ROOT_DIR
    / "models"
    / "fusion_demo"
    / "fusion_pipeline.joblib"
)

FUSION_FEATURE_COLUMNS_PATH = (
    ROOT_DIR
    / "models"
    / "fusion_demo"
    / "feature_columns.json"
)


# =============================================================================
# PRETRAINED MODELS
# =============================================================================

TEXT_MODEL_PATH = (
    ROOT_DIR
    / "models"
    / "all-mpnet-base-v2"
)

WAVLM_MODEL_PATH = (
    ROOT_DIR
    / "models"
    / "wavlm-base-plus"
)

CLIP_MODEL_PATH = (
    ROOT_DIR
    / "models"
    / "clip-vit-large-patch14"
)


# =============================================================================
# WEBCAM-CALIBRATED IMAGE MODEL
# =============================================================================

WEBCAM_IMAGE_MODEL_PATH = (
    ROOT_DIR
    / "models"
    / "image_demo"
    / "image_pipeline_webcam_calibrated.joblib"
)

WEBCAM_IMAGE_FEATURE_COLUMNS_PATH = (
    ROOT_DIR
    / "models"
    / "image_demo"
    / "feature_columns.json"
)

WEBCAM_IMAGE_METADATA_PATH = (
    ROOT_DIR
    / "models"
    / "image_demo"
    / "webcam_calibrated_metadata.json"
)


# =============================================================================
# CONFIGURATION
# =============================================================================

TARGET_SR = 16000

MAX_AUDIO_SECONDS = 20


# Backward-compatible alias.
#
# LABELS from temporal_fusion.py is the canonical source.
CLASSES = list(
    LABELS
)


WEBCAM_PROBABILITY_COLUMNS = [
    "image_webcam_focused_prob",
    "image_webcam_distracted_prob",
    "image_webcam_fatigued_prob",
    "image_webcam_overloaded_prob",
]

WEBCAM_CONFIDENCE_COLUMNS = [
    "image_webcam_top_probability",
    "image_webcam_confidence_gap",
]

EXPECTED_WEBCAM_FUSION_COLUMNS = {
    *WEBCAM_PROBABILITY_COLUMNS,
    *WEBCAM_CONFIDENCE_COLUMNS,
}


# =============================================================================
# GENERAL UTILITIES
# =============================================================================

def get_device() -> torch.device:
    """
    Return the device used by the pretrained neural models.
    """

    return torch.device(
        (
            "cuda"
            if torch.cuda.is_available()
            else "cpu"
        )
    )


def safe_mean(
    values: list[float],
) -> float:
    """
    Arithmetic mean with an empty-list fallback.
    """

    return (
        statistics.mean(
            values
        )
        if values
        else 0.0
    )


def safe_std(
    values: list[float],
) -> float:
    """
    Sample standard deviation with a small-sample fallback.
    """

    return (
        statistics.stdev(
            values
        )
        if len(values) >= 2
        else 0.0
    )


def normalise_label(
    value: Any,
) -> str:
    """
    Convert an arbitrary class label into the canonical textual format.
    """

    if value is None:

        return ""

    return (
        str(value)
        .strip()
        .lower()
    )


def clean_float(
    value: Any,
) -> float:
    """
    Convert an arbitrary value into a finite floating-point number.

    Invalid / NaN / +/- infinity values become 0.0.

    This function is intended primarily for FEATURES.

    Probability sanitisation itself is handled by
    temporal_fusion.normalise_probability_dict().
    """

    try:

        numeric = float(
            value
        )

        if np.isfinite(
            numeric
        ):

            return numeric

    except (
        TypeError,
        ValueError,
        OverflowError,
    ):

        pass

    return 0.0


def load_json_list(
    path: Path,
) -> list[str]:
    """
    Strictly load a JSON list of strings.
    """

    path = Path(
        path
    )

    if not path.exists():

        raise FileNotFoundError(
            f"JSON list file not found:\n{path}"
        )

    try:

        with path.open(
            "r",
            encoding="utf-8",
        ) as file_handle:

            value = json.load(
                file_handle
            )

    except Exception as exc:

        raise ValueError(
            f"Could not parse JSON list:\n{path}\n{exc}"
        ) from exc

    if not isinstance(
        value,
        list,
    ):

        raise ValueError(
            f"Expected a JSON list:\n{path}"
        )

    result = [
        str(item).strip()
        for item in value
    ]

    if any(
        not item
        for item in result
    ):

        raise ValueError(
            f"JSON list contains an empty value:\n{path}"
        )

    return result


def load_optional_json_object(
    path: Path,
) -> dict[str, Any]:
    """
    Load an optional JSON metadata object.

    Metadata is diagnostic only; absence does not prevent inference.
    """

    path = Path(
        path
    )

    if not path.exists():

        return {}

    try:

        with path.open(
            "r",
            encoding="utf-8",
        ) as file_handle:

            value = json.load(
                file_handle
            )

        if isinstance(
            value,
            dict,
        ):

            return value

    except Exception:

        pass

    return {}


def get_model_classes(
    model: Any,
) -> list[str]:
    """
    Obtain class ordering from a classifier or sklearn Pipeline.
    """

    classes = getattr(
        model,
        "classes_",
        None,
    )

    if classes is not None:

        return [
            normalise_label(
                label
            )
            for label in classes
        ]

    if hasattr(
        model,
        "named_steps",
    ):

        for step in reversed(
            list(
                model.named_steps.values()
            )
        ):

            classes = getattr(
                step,
                "classes_",
                None,
            )

            if classes is not None:

                return [
                    normalise_label(
                        label
                    )
                    for label in classes
                ]

    return []


def softmax(
    values: np.ndarray,
) -> np.ndarray:
    """
    Numerically stable softmax.

    Used only when a classifier provides decision_function(...)
    instead of predict_proba(...).
    """

    values = np.asarray(
        values,
        dtype=np.float64,
    ).reshape(
        -1
    )

    if values.size == 0:

        raise ValueError(
            "Cannot apply softmax to an empty score vector."
        )

    values = np.nan_to_num(
        values,
        nan=0.0,
        posinf=0.0,
        neginf=0.0,
    )

    values = (
        values
        - np.max(
            values
        )
    )

    exp_values = np.exp(
        values
    )

    total = float(
        np.sum(
            exp_values
        )
    )

    if (
        not np.isfinite(
            total
        )
        or
        total <= 0.0
    ):

        return (
            np.ones_like(
                exp_values,
                dtype=np.float64,
            )
            / len(
                exp_values
            )
        )

    return (
        exp_values
        / total
    )


# =============================================================================
# FINAL MULTIMODAL INFERENCE
# =============================================================================

class FinalMultimodalInference:
    """
    Canonical stateless SenseFuzeAI multimodal inference engine.

    One call to predict(...) represents exactly ONE multimodal observation.

    No temporal state is stored here.
    """

    def __init__(
        self,
    ) -> None:

        # ---------------------------------------------------------------------
        # Validate required artifacts
        # ---------------------------------------------------------------------

        required_paths = {
            "Fusion model":
                FUSION_MODEL_PATH,

            "Fusion feature schema":
                FUSION_FEATURE_COLUMNS_PATH,

            "MPNet model":
                TEXT_MODEL_PATH,

            "WavLM model":
                WAVLM_MODEL_PATH,

            "CLIP model":
                CLIP_MODEL_PATH,
        }

        for name, path in required_paths.items():

            if not path.exists():

                raise FileNotFoundError(
                    f"{name} not found:\n{path}"
                )

        # ---------------------------------------------------------------------
        # Device
        # ---------------------------------------------------------------------

        self.device = (
            get_device()
        )

        # ---------------------------------------------------------------------
        # Fusion classifier
        # ---------------------------------------------------------------------

        self.fusion_model = (
            joblib.load(
                FUSION_MODEL_PATH
            )
        )

        self.feature_columns = (
            load_json_list(
                FUSION_FEATURE_COLUMNS_PATH
            )
        )

        if not self.feature_columns:

            raise ValueError(
                "Fusion feature schema is empty."
            )

        if (
            len(
                set(
                    self.feature_columns
                )
            )
            != len(
                self.feature_columns
            )
        ):

            raise ValueError(
                "Fusion feature schema contains duplicate column names."
            )

        # ---------------------------------------------------------------------
        # Text model
        # ---------------------------------------------------------------------

        self.text_model = (
            SentenceTransformer(
                str(
                    TEXT_MODEL_PATH
                )
            )
        )

        # ---------------------------------------------------------------------
        # Audio model
        # ---------------------------------------------------------------------

        self.wavlm_extractor = (
            Wav2Vec2FeatureExtractor
            .from_pretrained(
                str(
                    WAVLM_MODEL_PATH
                )
            )
        )

        self.wavlm_model = (
            WavLMModel
            .from_pretrained(
                str(
                    WAVLM_MODEL_PATH
                )
            )
            .to(
                self.device
            )
        )

        self.wavlm_model.eval()

        # ---------------------------------------------------------------------
        # CLIP image model
        # ---------------------------------------------------------------------

        self.clip_processor = (
            CLIPProcessor
            .from_pretrained(
                str(
                    CLIP_MODEL_PATH
                )
            )
        )

        self.clip_model = (
            CLIPModel
            .from_pretrained(
                str(
                    CLIP_MODEL_PATH
                )
            )
            .to(
                self.device
            )
        )

        self.clip_model.eval()

        # ---------------------------------------------------------------------
        # Webcam-calibrated image classifier
        # ---------------------------------------------------------------------

        self.webcam_image_model = None

        self.webcam_image_feature_columns: list[
            str
        ] = []

        self.webcam_image_metadata: dict[
            str,
            Any
        ] = {}

        self._load_webcam_calibration_model()

        # ---------------------------------------------------------------------
        # Expected embedding dimensions from fusion schema
        # ---------------------------------------------------------------------

        self.expected_text_embedding_dim: int | None = None
        self.expected_wavlm_embedding_dim: int | None = None
        self.expected_clip_embedding_dim: int | None = None

        # ---------------------------------------------------------------------
        # Validate runtime/training compatibility
        # ---------------------------------------------------------------------

        self._validate_runtime_schema()

    # =========================================================================
    # INITIALISATION HELPERS
    # =========================================================================

    @staticmethod
    def _schema_embedding_dimension(
        columns: list[str],
        prefix: str,
    ) -> int | None:
        """
        Derive the expected embedding dimension from a contiguous schema:

            prefix0
            prefix1
            ...
            prefixN
        """

        matching = [
            column
            for column in columns
            if column.startswith(
                prefix
            )
        ]

        if not matching:

            return None

        indices: list[
            int
        ] = []

        for column in matching:

            suffix = column[
                len(prefix):
            ]

            if not suffix.isdigit():

                raise ValueError(
                    "Invalid embedding feature column: "
                    f"{column}"
                )

            indices.append(
                int(
                    suffix
                )
            )

        indices.sort()

        expected_indices = list(
            range(
                indices[-1] + 1
            )
        )

        if indices != expected_indices:

            raise ValueError(
                f"Non-contiguous embedding schema for '{prefix}'.\n"
                f"Observed indices begin/end: "
                f"{indices[:5]} ... {indices[-5:]}"
            )

        return (
            indices[-1]
            + 1
        )

    @staticmethod
    def _validate_model_feature_schema(
        model: Any,
        feature_columns: list[str],
        model_name: str,
    ) -> None:
        """
        Validate sklearn feature-count/name metadata when available.
        """

        expected_count = len(
            feature_columns
        )

        n_features = getattr(
            model,
            "n_features_in_",
            None,
        )

        if (
            n_features is not None
            and
            int(
                n_features
            )
            != expected_count
        ):

            raise ValueError(
                f"{model_name} feature-count mismatch.\n"
                f"Model expects: {int(n_features)}\n"
                f"Saved schema contains: {expected_count}"
            )

        feature_names = getattr(
            model,
            "feature_names_in_",
            None,
        )

        if feature_names is not None:

            model_columns = [
                str(
                    value
                )
                for value in feature_names
            ]

            if (
                model_columns
                != feature_columns
            ):

                raise ValueError(
                    f"{model_name} feature-name/order mismatch "
                    "between the trained model and saved schema."
                )

    @staticmethod
    def _validate_model_classes(
        model: Any,
        model_name: str,
    ) -> list[str]:
        """
        Enforce the canonical four-class behavioural output contract.
        """

        classes = (
            get_model_classes(
                model
            )
        )

        if not classes:

            raise ValueError(
                f"{model_name} does not expose classifier class ordering."
            )

        if len(classes) != len(
            LABELS
        ):

            raise ValueError(
                f"{model_name} class-count mismatch.\n"
                f"Expected: {len(LABELS)}\n"
                f"Observed: {len(classes)}\n"
                f"Observed classes: {classes}"
            )

        if set(
            classes
        ) != set(
            LABELS
        ):

            raise ValueError(
                f"{model_name} class-label mismatch.\n"
                f"Expected: {list(LABELS)}\n"
                f"Observed: {classes}"
            )

        return classes

    def _load_webcam_calibration_model(
        self,
    ) -> None:
        """
        Load the separately preserved webcam-calibrated image classifier.

        It is required only if the fusion feature schema contains
        image_webcam_* columns.
        """

        fusion_webcam_columns = {
            column
            for column in self.feature_columns
            if column.startswith(
                "image_webcam_"
            )
        }

        if not fusion_webcam_columns:

            return

        if (
            fusion_webcam_columns
            != EXPECTED_WEBCAM_FUSION_COLUMNS
        ):

            missing = (
                EXPECTED_WEBCAM_FUSION_COLUMNS
                - fusion_webcam_columns
            )

            unexpected = (
                fusion_webcam_columns
                - EXPECTED_WEBCAM_FUSION_COLUMNS
            )

            raise ValueError(
                "Fusion schema contains an incomplete or unsupported "
                "webcam-calibration feature set.\n"
                f"Missing: {sorted(missing)}\n"
                f"Unexpected: {sorted(unexpected)}"
            )

        if not WEBCAM_IMAGE_MODEL_PATH.exists():

            raise FileNotFoundError(
                "Fusion model expects webcam-calibrated image features, "
                "but the calibrated image classifier is missing:\n"
                f"{WEBCAM_IMAGE_MODEL_PATH}"
            )

        if not WEBCAM_IMAGE_FEATURE_COLUMNS_PATH.exists():

            raise FileNotFoundError(
                "Fusion model expects webcam-calibrated image features, "
                "but its image feature schema is missing:\n"
                f"{WEBCAM_IMAGE_FEATURE_COLUMNS_PATH}"
            )

        self.webcam_image_feature_columns = (
            load_json_list(
                WEBCAM_IMAGE_FEATURE_COLUMNS_PATH
            )
        )

        if not self.webcam_image_feature_columns:

            raise ValueError(
                "Webcam-calibrated image feature schema is empty."
            )

        if (
            len(
                set(
                    self.webcam_image_feature_columns
                )
            )
            != len(
                self.webcam_image_feature_columns
            )
        ):

            raise ValueError(
                "Webcam-calibrated image feature schema "
                "contains duplicate columns."
            )

        self.webcam_image_model = (
            joblib.load(
                WEBCAM_IMAGE_MODEL_PATH
            )
        )

        self.webcam_image_metadata = (
            load_optional_json_object(
                WEBCAM_IMAGE_METADATA_PATH
            )
        )

    def _validate_runtime_schema(
        self,
    ) -> None:
        """
        Validate the relationship between:

            - saved feature schema
            - fusion classifier
            - pretrained embedding dimensions
            - calibrated image classifier
            - behavioural classes

        This executes once during initialisation so incompatible artifacts
        fail early instead of producing misleading predictions.
        """

        # ---------------------------------------------------------------------
        # Fusion classifier class contract
        # ---------------------------------------------------------------------

        self._validate_model_classes(
            self.fusion_model,
            "Fusion classifier",
        )

        # ---------------------------------------------------------------------
        # Fusion feature contract
        # ---------------------------------------------------------------------

        self._validate_model_feature_schema(
            self.fusion_model,
            self.feature_columns,
            "Fusion classifier",
        )

        # ---------------------------------------------------------------------
        # Derive expected embedding dimensions from saved fusion schema
        # ---------------------------------------------------------------------

        self.expected_text_embedding_dim = (
            self._schema_embedding_dimension(
                self.feature_columns,
                "text_mpnet_emb_",
            )
        )

        self.expected_wavlm_embedding_dim = (
            self._schema_embedding_dimension(
                self.feature_columns,
                "audio_wavlm_emb_",
            )
        )

        self.expected_clip_embedding_dim = (
            self._schema_embedding_dimension(
                self.feature_columns,
                "image_clip_emb_",
            )
        )

        # ---------------------------------------------------------------------
        # MPNet embedding dimension
        # ---------------------------------------------------------------------

        if (
            self.expected_text_embedding_dim
            is not None
        ):

            runtime_text_dim = (
                self.text_model
                .get_sentence_embedding_dimension()
            )

            if (
                runtime_text_dim is not None
                and
                int(
                    runtime_text_dim
                )
                != self.expected_text_embedding_dim
            ):

                raise ValueError(
                    "MPNet embedding dimension does not match "
                    "the trained fusion schema.\n"
                    f"Runtime MPNet: {runtime_text_dim}\n"
                    f"Fusion schema: {self.expected_text_embedding_dim}"
                )

        # ---------------------------------------------------------------------
        # WavLM embedding dimension
        # ---------------------------------------------------------------------

        if (
            self.expected_wavlm_embedding_dim
            is not None
        ):

            runtime_wavlm_dim = int(
                self.wavlm_model
                .config
                .hidden_size
            )

            if (
                runtime_wavlm_dim
                != self.expected_wavlm_embedding_dim
            ):

                raise ValueError(
                    "WavLM embedding dimension does not match "
                    "the trained fusion schema.\n"
                    f"Runtime WavLM: {runtime_wavlm_dim}\n"
                    f"Fusion schema: {self.expected_wavlm_embedding_dim}"
                )

        # ---------------------------------------------------------------------
        # CLIP projected embedding dimension
        # ---------------------------------------------------------------------

        if (
            self.expected_clip_embedding_dim
            is not None
        ):

            runtime_clip_dim = getattr(
                self.clip_model.config,
                "projection_dim",
                None,
            )

            if (
                runtime_clip_dim is not None
                and
                int(
                    runtime_clip_dim
                )
                != self.expected_clip_embedding_dim
            ):

                raise ValueError(
                    "CLIP embedding dimension does not match "
                    "the trained fusion schema.\n"
                    f"Runtime CLIP: {runtime_clip_dim}\n"
                    f"Fusion schema: {self.expected_clip_embedding_dim}"
                )

        # ---------------------------------------------------------------------
        # Webcam-calibrated classifier
        # ---------------------------------------------------------------------

        if (
            self.webcam_image_model
            is not None
        ):

            self._validate_model_classes(
                self.webcam_image_model,
                "Webcam-calibrated image classifier",
            )

            self._validate_model_feature_schema(
                self.webcam_image_model,
                self.webcam_image_feature_columns,
                "Webcam-calibrated image classifier",
            )

        # ---------------------------------------------------------------------
        # Runtime summary
        # ---------------------------------------------------------------------

        print(
            "FinalMultimodalInference initialised successfully."
        )

        print(
            f"Device: {self.device}"
        )

        print(
            f"Fusion features: {len(self.feature_columns)}"
        )

        print(
            "Canonical classes:",
            list(
                LABELS
            ),
        )

        print(
            "Expected MPNet dimension:",
            self.expected_text_embedding_dim,
        )

        print(
            "Expected WavLM dimension:",
            self.expected_wavlm_embedding_dim,
        )

        print(
            "Expected CLIP dimension:",
            self.expected_clip_embedding_dim,
        )

        print(
            "Webcam-calibrated image augmentation:",
            (
                "enabled"
                if self.webcam_image_model
                is not None
                else "not required"
            ),
        )

        print(
            "Temporal inference:",
            (
                "external "
                "(temporal_fusion.py)"
            ),
        )

    # =========================================================================
    # PROBABILITY HELPERS
    # =========================================================================

    def _predict_probability_dict(
        self,
        model: Any,
        X: pd.DataFrame,
        *,
        model_name: str,
    ) -> dict[str, float]:
        """
        Return one canonical four-class probability distribution.

        Priority:

            1. predict_proba(...)
            2. decision_function(...) -> softmax
            3. predict(...) -> one-hot

        All final probability sanitisation / class restriction is delegated
        to temporal_fusion.normalise_probability_dict().
        """

        model_classes = (
            get_model_classes(
                model
            )
        )

        if (
            model_classes
            and
            set(
                model_classes
            )
            != set(
                LABELS
            )
        ):

            raise ValueError(
                f"{model_name} returned unexpected classes: "
                f"{model_classes}"
            )

        raw_probabilities: dict[
            str,
            Any
        ] = {}

        # ---------------------------------------------------------------------
        # predict_proba
        # ---------------------------------------------------------------------

        if hasattr(
            model,
            "predict_proba",
        ):

            if not model_classes:

                raise ValueError(
                    f"{model_name} provides predict_proba(...) "
                    "but exposes no class ordering."
                )

            values = np.asarray(
                model.predict_proba(
                    X
                )[0],
                dtype=np.float64,
            ).reshape(
                -1
            )

            if len(values) != len(
                model_classes
            ):

                raise ValueError(
                    f"{model_name} probability/class dimension mismatch.\n"
                    f"Probabilities: {len(values)}\n"
                    f"Classes: {len(model_classes)}"
                )

            raw_probabilities = {
                class_name:
                    clean_float(
                        probability
                    )
                for class_name, probability
                in zip(
                    model_classes,
                    values,
                )
            }

        # ---------------------------------------------------------------------
        # decision_function
        # ---------------------------------------------------------------------

        elif hasattr(
            model,
            "decision_function",
        ):

            if not model_classes:

                raise ValueError(
                    f"{model_name} provides decision_function(...) "
                    "but exposes no class ordering."
                )

            scores = np.asarray(
                model.decision_function(
                    X
                ),
                dtype=np.float64,
            )

            if scores.ndim > 1:

                scores = scores[
                    0
                ]

            scores = np.asarray(
                scores,
                dtype=np.float64,
            ).reshape(
                -1
            )

            if len(scores) != len(
                model_classes
            ):

                raise ValueError(
                    f"{model_name} decision-score/class dimension mismatch.\n"
                    f"Scores: {len(scores)}\n"
                    f"Classes: {len(model_classes)}"
                )

            values = softmax(
                scores
            )

            raw_probabilities = {
                class_name:
                    clean_float(
                        probability
                    )
                for class_name, probability
                in zip(
                    model_classes,
                    values,
                )
            }

        # ---------------------------------------------------------------------
        # Predict-only fallback
        # ---------------------------------------------------------------------

        else:

            predicted_label = normalise_label(
                model.predict(
                    X
                )[0]
            )

            if predicted_label not in LABELS:

                raise ValueError(
                    f"{model_name} predicted unsupported class: "
                    f"{predicted_label}"
                )

            raw_probabilities = {
                label:
                    (
                        1.0
                        if label
                        == predicted_label
                        else 0.0
                    )
                for label in LABELS
            }

        # ---------------------------------------------------------------------
        # Canonical exact four-class output
        # ---------------------------------------------------------------------

        probabilities = (
            normalise_probability_dict(
                raw_probabilities,
                labels=LABELS,
            )
        )

        validation = (
            validate_probability_distribution(
                probabilities,
                labels=LABELS,
                tolerance=(
                    PROBABILITY_SUM_TOLERANCE
                ),
            )
        )

        if not validation[
            "valid"
        ]:

            raise ValueError(
                f"{model_name} produced an invalid probability "
                f"distribution after normalisation: {validation}"
            )

        return probabilities

    # =========================================================================
    # KEYSTROKE FEATURES
    # =========================================================================

    def extract_keystroke_features(
        self,
        keystroke_json_path: Path,
    ) -> dict[str, Any]:
        """
        Load already-extracted keystroke features from a session JSON.

        Both original and keystroke_-prefixed aliases are returned so the
        inference runtime remains compatible with the fusion training schema.
        """

        keystroke_json_path = Path(
            keystroke_json_path
        )

        if not keystroke_json_path.exists():

            raise FileNotFoundError(
                "Keystroke JSON not found:\n"
                f"{keystroke_json_path}"
            )

        with keystroke_json_path.open(
            "r",
            encoding="utf-8",
        ) as file_handle:

            data = json.load(
                file_handle
            )

        if (
            not isinstance(
                data,
                dict,
            )
            or
            "features"
            not in data
        ):

            raise ValueError(
                "Keystroke JSON does not contain a 'features' field. "
                "Use a JSON generated by the session collector/live GUI."
            )

        raw_features = (
            data[
                "features"
            ]
        )

        if not isinstance(
            raw_features,
            dict,
        ):

            raise ValueError(
                "Keystroke 'features' must be a JSON object."
            )

        output: dict[
            str,
            float
        ] = {}

        for key, value in raw_features.items():

            key_name = str(
                key
            )

            clean_value = (
                clean_float(
                    value
                )
            )

            # Preserve the original feature.
            output[
                key_name
            ] = clean_value

            # Expose the fusion-training prefixed alias.
            if not key_name.startswith(
                "keystroke_"
            ):

                output[
                    f"keystroke_{key_name}"
                ] = clean_value

        return output

    # =========================================================================
    # TEXT FEATURES
    # =========================================================================

    def extract_text_features(
        self,
        text: str,
    ) -> dict[str, float]:
        """
        Extract a normalised MPNet sentence embedding.
        """

        text = str(
            text
        ).strip()

        if not text:

            raise ValueError(
                "Text input is empty."
            )

        embedding = (
            self.text_model.encode(
                [text],
                normalize_embeddings=True,
                show_progress_bar=False,
                convert_to_numpy=True,
            )[0]
        )

        embedding = np.asarray(
            embedding,
            dtype=np.float32,
        ).reshape(
            -1
        )

        if (
            self.expected_text_embedding_dim
            is not None
            and
            embedding.size
            != self.expected_text_embedding_dim
        ):

            raise ValueError(
                "Runtime MPNet embedding dimension mismatch.\n"
                f"Expected: {self.expected_text_embedding_dim}\n"
                f"Observed: {embedding.size}"
            )

        return {
            f"text_mpnet_emb_{index}":
                clean_float(
                    value
                )
            for index, value
            in enumerate(
                embedding
            )
        }

    # =========================================================================
    # AUDIO FEATURES
    # =========================================================================

    def extract_audio_features(
        self,
        audio_path: Path,
    ) -> dict[str, float]:
        """
        Extract classical acoustic features plus a normalised WavLM embedding.

        Maximum audio duration must remain aligned with the training feature
        extractor.
        """

        audio_path = Path(
            audio_path
        )

        if not audio_path.exists():

            raise FileNotFoundError(
                "Audio file not found:\n"
                f"{audio_path}"
            )

        waveform, sample_rate = (
            librosa.load(
                audio_path,
                sr=TARGET_SR,
                mono=True,
            )
        )

        waveform = np.asarray(
            waveform,
            dtype=np.float32,
        )

        if waveform.size == 0:

            raise ValueError(
                "Empty audio file:\n"
                f"{audio_path}"
            )

        # ---------------------------------------------------------------------
        # Match training-time maximum duration.
        # ---------------------------------------------------------------------

        waveform = waveform[
            :
            TARGET_SR
            * MAX_AUDIO_SECONDS
        ]

        duration = (
            librosa.get_duration(
                y=waveform,
                sr=sample_rate,
            )
        )

        # ---------------------------------------------------------------------
        # Classical acoustic features
        # ---------------------------------------------------------------------

        rms = (
            librosa.feature.rms(
                y=waveform
            )[0]
        )

        zcr = (
            librosa.feature
            .zero_crossing_rate(
                waveform
            )[0]
        )

        mfcc = (
            librosa.feature.mfcc(
                y=waveform,
                sr=sample_rate,
                n_mfcc=13,
            )
        )

        spectral_centroid = (
            librosa.feature
            .spectral_centroid(
                y=waveform,
                sr=sample_rate,
            )[0]
        )

        spectral_bandwidth = (
            librosa.feature
            .spectral_bandwidth(
                y=waveform,
                sr=sample_rate,
            )[0]
        )

        spectral_rolloff = (
            librosa.feature
            .spectral_rolloff(
                y=waveform,
                sr=sample_rate,
            )[0]
        )

        pitches, magnitudes = (
            librosa.piptrack(
                y=waveform,
                sr=sample_rate,
            )
        )

        positive_magnitudes = (
            magnitudes[
                magnitudes > 0
            ]
        )

        if positive_magnitudes.size > 0:

            threshold = float(
                np.median(
                    positive_magnitudes
                )
            )

        else:

            threshold = 0.0

        pitch_values = pitches[
            magnitudes > threshold
        ]

        pitch_values = pitch_values[
            pitch_values > 0
        ]

        features: dict[
            str,
            float
        ] = {
            "audio_duration":
                clean_float(
                    duration
                ),

            "audio_rms_mean":
                clean_float(
                    np.mean(
                        rms
                    )
                ),

            "audio_rms_std":
                clean_float(
                    np.std(
                        rms
                    )
                ),

            "audio_zcr_mean":
                clean_float(
                    np.mean(
                        zcr
                    )
                ),

            "audio_zcr_std":
                clean_float(
                    np.std(
                        zcr
                    )
                ),

            "audio_spectral_centroid_mean":
                clean_float(
                    np.mean(
                        spectral_centroid
                    )
                ),

            "audio_spectral_centroid_std":
                clean_float(
                    np.std(
                        spectral_centroid
                    )
                ),

            "audio_spectral_bandwidth_mean":
                clean_float(
                    np.mean(
                        spectral_bandwidth
                    )
                ),

            "audio_spectral_bandwidth_std":
                clean_float(
                    np.std(
                        spectral_bandwidth
                    )
                ),

            "audio_spectral_rolloff_mean":
                clean_float(
                    np.mean(
                        spectral_rolloff
                    )
                ),

            "audio_spectral_rolloff_std":
                clean_float(
                    np.std(
                        spectral_rolloff
                    )
                ),

            "audio_pitch_mean":
                (
                    clean_float(
                        np.mean(
                            pitch_values
                        )
                    )
                    if pitch_values.size > 0
                    else 0.0
                ),

            "audio_pitch_std":
                (
                    clean_float(
                        np.std(
                            pitch_values
                        )
                    )
                    if pitch_values.size > 0
                    else 0.0
                ),

            "audio_pitch_min":
                (
                    clean_float(
                        np.min(
                            pitch_values
                        )
                    )
                    if pitch_values.size > 0
                    else 0.0
                ),

            "audio_pitch_max":
                (
                    clean_float(
                        np.max(
                            pitch_values
                        )
                    )
                    if pitch_values.size > 0
                    else 0.0
                ),
        }

        # ---------------------------------------------------------------------
        # MFCC
        # ---------------------------------------------------------------------

        for index in range(
            13
        ):

            features[
                f"audio_mfcc_{index}_mean"
            ] = clean_float(
                np.mean(
                    mfcc[
                        index
                    ]
                )
            )

            features[
                f"audio_mfcc_{index}_std"
            ] = clean_float(
                np.std(
                    mfcc[
                        index
                    ]
                )
            )

        # ---------------------------------------------------------------------
        # WavLM
        # ---------------------------------------------------------------------

        inputs = (
            self.wavlm_extractor(
                waveform,
                sampling_rate=TARGET_SR,
                return_tensors="pt",
                padding=True,
            )
        )

        inputs = {
            key:
                value.to(
                    self.device
                )
            for key, value
            in inputs.items()
        }

        with torch.inference_mode():

            outputs = (
                self.wavlm_model(
                    **inputs
                )
            )

        hidden_state = (
            outputs
            .last_hidden_state
        )

        # One unpadded waveform is used per prediction, therefore mean
        # pooling over the temporal dimension matches the existing training
        # extraction behaviour.
        embedding = (
            hidden_state
            .mean(
                dim=1
            )
            .squeeze(0)
        )

        embedding = F.normalize(
            embedding,
            p=2,
            dim=0,
        )

        embedding = (
            embedding
            .detach()
            .cpu()
            .numpy()
        )

        embedding = np.asarray(
            embedding,
            dtype=np.float32,
        ).reshape(
            -1
        )

        if (
            self.expected_wavlm_embedding_dim
            is not None
            and
            embedding.size
            != self.expected_wavlm_embedding_dim
        ):

            raise ValueError(
                "Runtime WavLM embedding dimension mismatch.\n"
                f"Expected: {self.expected_wavlm_embedding_dim}\n"
                f"Observed: {embedding.size}"
            )

        for index, value in enumerate(
            embedding
        ):

            features[
                f"audio_wavlm_emb_{index}"
            ] = clean_float(
                value
            )

        return features

    # =========================================================================
    # CLIP EMBEDDING
    # =========================================================================

    def extract_clip_embedding(
        self,
        image: Image.Image,
    ) -> np.ndarray:
        """
        Extract exactly one L2-normalised CLIP projected image embedding.

        The same embedding is used by:

            - fusion image features
            - webcam-calibrated image classifier
        """

        image = image.convert(
            "RGB"
        )

        inputs = (
            self.clip_processor(
                images=image,
                return_tensors="pt",
            )
        )

        pixel_values = (
            inputs[
                "pixel_values"
            ]
            .to(
                self.device
            )
        )

        with torch.inference_mode():

            output = (
                self.clip_model
                .get_image_features(
                    pixel_values=(
                        pixel_values
                    )
                )
            )

        # Transformers versions may return either a Tensor or a wrapper.
        if isinstance(
            output,
            torch.Tensor,
        ):

            image_features = (
                output
            )

        elif hasattr(
            output,
            "image_embeds",
        ):

            image_features = (
                output.image_embeds
            )

        elif hasattr(
            output,
            "pooler_output",
        ):

            image_features = (
                output.pooler_output
            )

        elif hasattr(
            output,
            "last_hidden_state",
        ):

            image_features = (
                output
                .last_hidden_state
                .mean(
                    dim=1
                )
            )

        else:

            raise TypeError(
                "Unsupported CLIP image-feature output type: "
                f"{type(output)}"
            )

        image_features = (
            F.normalize(
                image_features,
                p=2,
                dim=-1,
            )
        )

        embedding = (
            image_features
            .squeeze(0)
            .detach()
            .cpu()
            .numpy()
        )

        embedding = np.asarray(
            embedding,
            dtype=np.float32,
        ).reshape(
            -1
        )

        if (
            self.expected_clip_embedding_dim
            is not None
            and
            embedding.size
            != self.expected_clip_embedding_dim
        ):

            raise ValueError(
                "Runtime CLIP embedding dimension mismatch.\n"
                f"Expected: {self.expected_clip_embedding_dim}\n"
                f"Observed: {embedding.size}"
            )

        return embedding

    # =========================================================================
    # WEBCAM-CALIBRATED IMAGE CLASSIFIER
    # =========================================================================

    def extract_webcam_calibration_features(
        self,
        clip_features: dict[str, float],
    ) -> dict[str, float]:
        """
        Convert the current image/frame CLIP representation into the exact
        six calibrated image features expected by the fusion model.
        """

        if self.webcam_image_model is None:

            return {}

        if not self.webcam_image_feature_columns:

            raise ValueError(
                "Webcam-calibrated image classifier is loaded, "
                "but its feature schema is missing."
            )

        missing = [
            column
            for column
            in self.webcam_image_feature_columns
            if column not in clip_features
        ]

        if missing:

            raise ValueError(
                "Webcam-calibrated image feature mismatch.\n"
                f"Missing CLIP columns: {missing[:20]}"
            )

        row = {
            column:
                clean_float(
                    clip_features[
                        column
                    ]
                )
            for column
            in self.webcam_image_feature_columns
        }

        X_image = pd.DataFrame(
            [row],
            columns=(
                self.webcam_image_feature_columns
            ),
        )

        probabilities = (
            self._predict_probability_dict(
                self.webcam_image_model,
                X_image,
                model_name=(
                    "Webcam-calibrated image classifier"
                ),
            )
        )

        summary = (
            summarise_probability_dict(
                probabilities,
                labels=LABELS,
            )
        )

        return {
            "image_webcam_focused_prob":
                probabilities[
                    "focused"
                ],

            "image_webcam_distracted_prob":
                probabilities[
                    "distracted"
                ],

            "image_webcam_fatigued_prob":
                probabilities[
                    "fatigued"
                ],

            "image_webcam_overloaded_prob":
                probabilities[
                    "overloaded"
                ],

            "image_webcam_top_probability":
                float(
                    summary[
                        "confidence"
                    ]
                ),

            "image_webcam_confidence_gap":
                float(
                    summary[
                        "confidence_gap"
                    ]
                ),
        }

    # =========================================================================
    # COMPLETE IMAGE FEATURES
    # =========================================================================

    def extract_image_features(
        self,
        image_path: Path,
    ) -> dict[str, float]:
        """
        Extract:

            image_clip_emb_*
            image_webcam_*

        from one image or captured video/webcam frame.
        """

        image_path = Path(
            image_path
        )

        if not image_path.exists():

            raise FileNotFoundError(
                "Image file not found:\n"
                f"{image_path}"
            )

        try:

            with Image.open(
                image_path
            ) as image_file:

                image = (
                    image_file
                    .convert(
                        "RGB"
                    )
                )

                embedding = (
                    self.extract_clip_embedding(
                        image
                    )
                )

        except Exception as exc:

            raise ValueError(
                "Could not decode/process image:\n"
                f"{image_path}\n{exc}"
            ) from exc

        clip_features = {
            f"image_clip_emb_{index}":
                clean_float(
                    value
                )
            for index, value
            in enumerate(
                embedding
            )
        }

        calibrated_features = (
            self.extract_webcam_calibration_features(
                clip_features
            )
        )

        return {
            **clip_features,
            **calibrated_features,
        }

    # =========================================================================
    # FUSION DATAFRAME
    # =========================================================================

    def build_fusion_dataframe(
        self,
        features: dict[str, Any],
    ) -> pd.DataFrame:
        """
        Build one fusion input row in EXACT saved training-feature order.

        Runtime features that are not part of the saved schema are ignored.
        Missing required features are fatal.
        """

        if not isinstance(
            features,
            dict,
        ):

            raise TypeError(
                "Fusion features must be supplied as a dictionary."
            )

        missing = [
            column
            for column
            in self.feature_columns
            if column not in features
        ]

        if missing:

            raise ValueError(
                "Fusion feature mismatch.\n\n"
                f"Expected feature count: {len(self.feature_columns)}\n"
                f"Available runtime features: {len(features)}\n"
                f"Missing feature count: {len(missing)}\n"
                f"Missing examples: {missing[:30]}"
            )

        row = {
            column:
                clean_float(
                    features[
                        column
                    ]
                )
            for column
            in self.feature_columns
        }

        dataframe = pd.DataFrame(
            [row],
            columns=(
                self.feature_columns
            ),
        )

        numeric_values = (
            dataframe
            .to_numpy(
                dtype=np.float64
            )
        )

        if not np.all(
            np.isfinite(
                numeric_values
            )
        ):

            raise ValueError(
                "Fusion input contains non-finite values "
                "after runtime sanitisation."
            )

        if (
            dataframe.shape[1]
            != len(
                self.feature_columns
            )
        ):

            raise ValueError(
                "Fusion dataframe dimension does not match saved schema."
            )

        return dataframe

    # =========================================================================
    # FUSION PREDICTION
    # =========================================================================

    def predict(
        self,
        keystroke_json: Path,
        text: str,
        audio_path: Path,
        image_path: Path,
    ) -> dict[str, Any]:
        """
        Produce ONE stateless multimodal fusion observation.

        Parameters
        ----------
        keystroke_json:
            Path to keystroke JSON containing a "features" object.

        text:
            Current textual input.

        audio_path:
            Current fixed audio source.

        image_path:
            Current image or video/webcam snapshot.

        Returns
        -------
        dict
            One canonical RAW multimodal prediction.

        Notes
        -----
        No temporal-history update occurs here.

        The returned ``probabilities`` dictionary should subsequently be
        supplied to TemporalFusionEngine by the desktop/web application.
        """

        features: dict[
            str,
            Any
        ] = {}

        # ---------------------------------------------------------------------
        # Extract all four modalities
        # ---------------------------------------------------------------------

        keystroke_features = (
            self.extract_keystroke_features(
                keystroke_json
            )
        )

        text_features = (
            self.extract_text_features(
                text
            )
        )

        audio_features = (
            self.extract_audio_features(
                audio_path
            )
        )

        image_features = (
            self.extract_image_features(
                image_path
            )
        )

        features.update(
            keystroke_features
        )

        features.update(
            text_features
        )

        features.update(
            audio_features
        )

        features.update(
            image_features
        )

        # ---------------------------------------------------------------------
        # Exact training-aligned fusion vector
        # ---------------------------------------------------------------------

        X = (
            self.build_fusion_dataframe(
                features
            )
        )

        # ---------------------------------------------------------------------
        # Native model prediction
        # ---------------------------------------------------------------------

        native_prediction = (
            normalise_label(
                self.fusion_model
                .predict(
                    X
                )[0]
            )
        )

        if native_prediction not in LABELS:

            raise ValueError(
                "Fusion classifier returned unsupported class: "
                f"{native_prediction}"
            )

        # ---------------------------------------------------------------------
        # Canonical exact four-class probability vector
        # ---------------------------------------------------------------------

        probabilities = (
            self._predict_probability_dict(
                self.fusion_model,
                X,
                model_name=(
                    "Fusion classifier"
                ),
            )
        )

        raw_summary = (
            summarise_probability_dict(
                probabilities,
                labels=LABELS,
            )
        )

        current_state = (
            raw_summary[
                "current_state"
            ]
        )

        confidence = float(
            raw_summary[
                "confidence"
            ]
        )

        second_class = (
            raw_summary[
                "second_class"
            ]
        )

        second_probability = float(
            raw_summary[
                "second_probability"
            ]
        )

        confidence_gap = float(
            raw_summary[
                "confidence_gap"
            ]
        )

        probability_validation = (
            validate_probability_distribution(
                probabilities,
                labels=LABELS,
                tolerance=(
                    PROBABILITY_SUM_TOLERANCE
                ),
            )
        )

        if not probability_validation[
            "valid"
        ]:

            raise ValueError(
                "Fusion probability contract failed validation: "
                f"{probability_validation}"
            )

        # ---------------------------------------------------------------------
        # Webcam-calibration diagnostics
        # ---------------------------------------------------------------------

        if (
            self.webcam_image_model
            is not None
        ):

            webcam_probabilities = {
                label:
                    clean_float(
                        image_features.get(
                            f"image_webcam_{label}_prob",
                            0.0,
                        )
                    )
                for label
                in LABELS
            }

            webcam_probabilities = (
                normalise_probability_dict(
                    webcam_probabilities,
                    labels=LABELS,
                )
            )

            webcam_summary = (
                summarise_probability_dict(
                    webcam_probabilities,
                    labels=LABELS,
                )
            )

            webcam_current_state = (
                webcam_summary[
                    "current_state"
                ]
            )

            webcam_top_probability = (
                webcam_summary[
                    "confidence"
                ]
            )

            webcam_confidence_gap = (
                webcam_summary[
                    "confidence_gap"
                ]
            )

        else:

            webcam_probabilities = {
                label:
                    None
                for label
                in LABELS
            }

            webcam_current_state = (
                None
            )

            webcam_top_probability = (
                None
            )

            webcam_confidence_gap = (
                None
            )

        # ---------------------------------------------------------------------
        # Canonical stateless result
        # ---------------------------------------------------------------------

        return {
            # -------------------------------------------------------------
            # Compatibility / native classifier prediction
            # -------------------------------------------------------------
            "prediction":
                native_prediction,

            "model_prediction":
                native_prediction,

            # -------------------------------------------------------------
            # Canonical RAW fusion result
            # -------------------------------------------------------------
            "current_state":
                current_state,

            "top_class":
                current_state,

            "confidence":
                confidence,

            "top_probability":
                confidence,

            "confidence_percent":
                round(
                    confidence
                    * 100.0,
                    2,
                ),

            "confidence_level":
                raw_summary[
                    "confidence_level"
                ],

            "second_class":
                second_class,

            "second_probability":
                second_probability,

            "confidence_gap":
                confidence_gap,

            "probabilities":
                probabilities,

            # -------------------------------------------------------------
            # Consistency diagnostics
            # -------------------------------------------------------------
            "prediction_matches_probability_argmax":
                (
                    native_prediction
                    == current_state
                ),

            "probability_validation":
                probability_validation,

            "probability_sum":
                probability_validation[
                    "probability_sum"
                ],

            # -------------------------------------------------------------
            # Explicit architectural declaration
            # -------------------------------------------------------------
            "inference_scope":
                "single_multimodal_observation",

            "temporal_fusion_applied":
                False,

            "temporal_backend":
                "temporal_fusion.TemporalFusionEngine",

            # -------------------------------------------------------------
            # Technical runtime information
            # -------------------------------------------------------------
            "feature_dimension":
                int(
                    X.shape[1]
                ),

            "device":
                str(
                    self.device
                ),

            "used_modalities": {
                "keystroke":
                    True,

                "text":
                    True,

                "audio":
                    True,

                "image":
                    True,

                "webcam_image_calibration":
                    (
                        self.webcam_image_model
                        is not None
                    ),
            },

            # -------------------------------------------------------------
            # Optional calibrated image diagnostic
            # -------------------------------------------------------------
            "image_calibration": {
                "enabled":
                    (
                        self.webcam_image_model
                        is not None
                    ),

                "current_state":
                    webcam_current_state,

                "probabilities":
                    webcam_probabilities,

                "top_probability":
                    webcam_top_probability,

                "confidence_gap":
                    webcam_confidence_gap,

                "model_path":
                    (
                        str(
                            WEBCAM_IMAGE_MODEL_PATH
                        )
                        if self.webcam_image_model
                        is not None
                        else None
                    ),

                "metadata":
                    self.webcam_image_metadata,
            },

            # -------------------------------------------------------------
            # Detailed traceability
            # -------------------------------------------------------------
            "technical_details": {
                "native_model_prediction":
                    native_prediction,

                "probability_argmax":
                    current_state,

                "prediction_consistent":
                    (
                        native_prediction
                        == current_state
                    ),

                "second_class":
                    second_class,

                "second_probability":
                    second_probability,

                "confidence_gap":
                    confidence_gap,

                "probability_sum":
                    probability_validation[
                        "probability_sum"
                    ],

                "probability_contract_valid":
                    probability_validation[
                        "valid"
                    ],

                "feature_dimension":
                    int(
                        X.shape[1]
                    ),

                "device":
                    str(
                        self.device
                    ),

                "fusion_model_path":
                    str(
                        FUSION_MODEL_PATH
                    ),

                "fusion_schema_path":
                    str(
                        FUSION_FEATURE_COLUMNS_PATH
                    ),

                "text_model_path":
                    str(
                        TEXT_MODEL_PATH
                    ),

                "audio_model_path":
                    str(
                        WAVLM_MODEL_PATH
                    ),

                "image_model_path":
                    str(
                        CLIP_MODEL_PATH
                    ),

                "webcam_calibration_enabled":
                    (
                        self.webcam_image_model
                        is not None
                    ),

                "expected_text_embedding_dim":
                    self.expected_text_embedding_dim,

                "expected_wavlm_embedding_dim":
                    self.expected_wavlm_embedding_dim,

                "expected_clip_embedding_dim":
                    self.expected_clip_embedding_dim,

                "temporal_fusion_applied":
                    False,
            },
        }


# =============================================================================
# COMMAND-LINE INTERFACE
# =============================================================================

def main() -> None:
    """
    Command-line entry point for ONE stateless multimodal prediction.

    Temporal fusion is intentionally not performed by this command.
    """

    parser = argparse.ArgumentParser(
        description=(
            "SenseFuzeAI canonical stateless multimodal "
            "behavioural-state inference pipeline. "
            "Temporal aggregation is performed separately by "
            "temporal_fusion.py."
        )
    )

    parser.add_argument(
        "--keystroke_json",
        required=True,
        type=Path,
        help=(
            "Path to a keystroke JSON containing "
            "a 'features' object."
        ),
    )

    parser.add_argument(
        "--text",
        required=True,
        type=str,
        help=(
            "Current text associated with this observation."
        ),
    )

    parser.add_argument(
        "--audio",
        required=True,
        type=Path,
        help=(
            "Path to the current audio source."
        ),
    )

    parser.add_argument(
        "--image",
        required=True,
        type=Path,
        help=(
            "Path to the current image or video/webcam snapshot."
        ),
    )

    parser.add_argument(
        "--output",
        default=None,
        type=Path,
        help=(
            "Optional JSON result output path."
        ),
    )

    args = (
        parser.parse_args()
    )

    inference = (
        FinalMultimodalInference()
    )

    result = (
        inference.predict(
            keystroke_json=(
                args.keystroke_json
            ),
            text=(
                args.text
            ),
            audio_path=(
                args.audio
            ),
            image_path=(
                args.image
            ),
        )
    )

    output_json = (
        json.dumps(
            result,
            indent=4,
        )
    )

    print()

    print(
        "=" * 80
    )

    print(
        "SenseFuzeAI "
        "Raw Multimodal Prediction"
    )

    print(
        "=" * 80
    )

    print(
        output_json
    )

    print()

    print(
        "NOTE: This is ONE raw multimodal observation. "
        "Temporal aggregation is applied externally "
        "by temporal_fusion.py."
    )

    if (
        args.output
        is not None
    ):

        args.output.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        args.output.write_text(
            output_json,
            encoding="utf-8",
        )

        print()

        print(
            "Prediction saved to:\n"
            f"{args.output}"
        )


# =============================================================================
# ENTRY POINT
# =============================================================================

if __name__ == "__main__":

    main()
