# === model_artifacts/live_text_test.py ===
# SenseFuzeAI - Live Text Model Test GUI
#
# Presentation-first version:
#   - main output shows concise prototype-friendly result
#   - technical details are available through "Show Technical Details"
#   - exports include both summary and full diagnostic information
#
# This script tests the trained text model generated by:
#   train_text_model.py
#
# Required files:
#   model_artifacts/text_model.joblib
#   model_artifacts/text_model_meta.json
#
# Behaviour prediction:
#   raw text -> TF-IDF features -> best selected classifier
#
# Sentiment prediction:
#   rule-based lexical sentiment scoring
#
# Export support:
#   - JSON full diagnostic result
#   - CSV compact summary
#   - TXT human-readable report

from __future__ import annotations

import csv
import json
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

import joblib
import tkinter as tk
from tkinter import scrolledtext, messagebox


# ============================================================
# Project paths
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parent.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

MODEL_DIR = PROJECT_ROOT / "model_artifacts"
MODEL_PATH = MODEL_DIR / "text_model.joblib"
META_PATH = MODEL_DIR / "text_model_meta.json"

EXPORT_DIR = MODEL_DIR / "exported_results"
EXPORT_DIR.mkdir(parents=True, exist_ok=True)


# ============================================================
# SenseFuzeAI behaviour classes
# ============================================================

BEHAVIOUR_CLASSES = [
    "focused",
    "distracted",
    "fatigued",
    "overloaded",
]


# ============================================================
# Sentiment lexicons
# ============================================================

POSITIVE_WORDS = {
    "good",
    "great",
    "calm",
    "clear",
    "steady",
    "confident",
    "comfortable",
    "productive",
    "focused",
    "focus",
    "motivated",
    "ready",
    "alert",
    "positive",
    "relaxed",
    "fine",
    "well",
    "happy",
    "satisfied",
    "organised",
    "organized",
    "controlled",
    "engaged",
    "stable",
    "progress",
    "smoothly",
    "effective",
    "efficient",
    "capable",
}

NEGATIVE_WORDS = {
    "bad",
    "tired",
    "fatigued",
    "drained",
    "exhausted",
    "sleepy",
    "slow",
    "overwhelmed",
    "overloaded",
    "stressed",
    "stress",
    "pressure",
    "anxious",
    "worried",
    "distracted",
    "unfocused",
    "confused",
    "frustrated",
    "difficult",
    "hard",
    "struggling",
    "cannot",
    "can't",
    "unable",
    "urgent",
    "too",
    "heavy",
    "weak",
    "lost",
    "scattered",
    "panic",
    "burnt",
    "burned",
    "deadline",
    "deadlines",
}


# ============================================================
# Runtime state
# ============================================================

latest_text_result: dict[str, Any] | None = None
latest_summary_text: str = ""
latest_technical_text: str = ""


# ============================================================
# Model loading
# ============================================================

def load_json(path: Path) -> dict[str, Any]:
    """
    Safely load model metadata.
    """
    if not path.exists():
        return {}

    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


def load_text_model() -> tuple[Any | None, dict[str, Any], str | None]:
    """
    Load the trained text model and metadata.

    Returns:
        model, metadata, error_message
    """
    if not MODEL_PATH.exists():
        return (
            None,
            {},
            (
                f"Text model not found:\n{MODEL_PATH}\n\n"
                "Please train the text model first by running:\n"
                "python train_text_model.py"
            ),
        )

    try:
        model = joblib.load(MODEL_PATH)
        metadata = load_json(META_PATH)
        return model, metadata, None

    except Exception as exc:
        return (
            None,
            {},
            f"Failed to load text model:\n{exc}",
        )


TEXT_MODEL, TEXT_META, MODEL_LOAD_ERROR = load_text_model()


# ============================================================
# General utilities
# ============================================================

def timestamp_for_filename() -> str:
    """
    Return a filesystem-safe timestamp.
    """
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def tokenize_text(text: str) -> list[str]:
    """
    Convert text into lowercase word tokens for lexical sentiment scoring.
    """
    return re.findall(r"[a-zA-Z']+", str(text).lower())


def get_model_classes(model: Any) -> list[str]:
    """
    Extract class order from the trained scikit-learn pipeline.
    """
    if model is None:
        return BEHAVIOUR_CLASSES

    classes = list(getattr(model, "classes_", []))

    if not classes and hasattr(model, "named_steps"):
        final_estimator = list(model.named_steps.values())[-1]
        classes = list(getattr(final_estimator, "classes_", []))

    if not classes:
        classes = BEHAVIOUR_CLASSES

    return [str(label) for label in classes]


def normalise_scores(scores: dict[str, float] | None) -> dict[str, float]:
    """
    Ensure probability scores are valid and sum to 1.
    """
    if not scores:
        return {
            label: 1.0 / len(BEHAVIOUR_CLASSES)
            for label in BEHAVIOUR_CLASSES
        }

    clean = {
        label: max(float(scores.get(label, 0.0)), 0.0)
        for label in BEHAVIOUR_CLASSES
    }

    total = sum(clean.values())

    if total <= 0:
        return {
            label: 1.0 / len(BEHAVIOUR_CLASSES)
            for label in BEHAVIOUR_CLASSES
        }

    return {
        label: value / total
        for label, value in clean.items()
    }


def get_best_label(scores: dict[str, float]) -> str:
    """
    Return the class with the highest score.
    """
    scores = normalise_scores(scores)
    return max(scores, key=scores.get)


def safe_float(value: Any) -> float | None:
    """
    Convert value to float if possible.
    """
    try:
        return float(value)
    except Exception:
        return None


def format_percent(value: float) -> str:
    """
    Convert probability value into percentage string.
    """
    safe = max(0.0, min(1.0, float(value)))
    return f"{safe * 100:.2f}%"


def format_scores_decimal(scores: dict[str, float]) -> str:
    """
    Format behaviour scores as decimal probabilities.
    """
    scores = normalise_scores(scores)

    lines = []

    for label, score in sorted(
        scores.items(),
        key=lambda item: item[1],
        reverse=True,
    ):
        lines.append(f"  {label}: {score:.4f}")

    return "\n".join(lines)


def format_scores_percent(scores: dict[str, float]) -> str:
    """
    Format behaviour scores as percentages for presentation output.
    """
    scores = normalise_scores(scores)

    label_width = max(len(label) for label in BEHAVIOUR_CLASSES)

    lines = []

    for label, score in sorted(
        scores.items(),
        key=lambda item: item[1],
        reverse=True,
    ):
        display_label = label.capitalize()
        lines.append(f"{display_label:<{label_width + 2}} {format_percent(score):>8}")

    return "\n".join(lines)


def require_latest_result() -> dict[str, Any] | None:
    """
    Ensure that a latest text result exists before exporting.
    """
    if latest_text_result is None:
        messagebox.showwarning(
            "No Result Available",
            "No text prediction result is available yet.\n\n"
            "Please run a text prediction first.",
        )
        return None

    return latest_text_result


# ============================================================
# Sentiment prediction
# ============================================================

def predict_text_sentiment(text: str) -> dict[str, Any]:
    """
    Estimate sentiment using a lightweight rule-based lexical method.
    """
    tokens = tokenize_text(text)

    positive_hits = [token for token in tokens if token in POSITIVE_WORDS]
    negative_hits = [token for token in tokens if token in NEGATIVE_WORDS]

    positive_count = len(positive_hits)
    negative_count = len(negative_hits)

    total_sentiment_hits = positive_count + negative_count

    if total_sentiment_hits == 0:
        return {
            "sentiment_label": "neutral",
            "sentiment_score": 1.0,
            "positive_count": 0,
            "negative_count": 0,
            "positive_hits": [],
            "negative_hits": [],
            "method": "rule_based_lexical_sentiment",
        }

    raw_score = (positive_count - negative_count) / total_sentiment_hits

    if raw_score > 0.15:
        sentiment_label = "positive"
        sentiment_score = abs(raw_score)
    elif raw_score < -0.15:
        sentiment_label = "negative"
        sentiment_score = abs(raw_score)
    else:
        sentiment_label = "neutral"
        sentiment_score = 1.0 - abs(raw_score)

    return {
        "sentiment_label": sentiment_label,
        "sentiment_score": float(sentiment_score),
        "positive_count": int(positive_count),
        "negative_count": int(negative_count),
        "positive_hits": positive_hits,
        "negative_hits": negative_hits,
        "method": "rule_based_lexical_sentiment",
    }


# ============================================================
# Behaviour prediction
# ============================================================

def predict_text_behaviour(text: str) -> dict[str, Any]:
    """
    Predict behavioural state from live text using text_model.joblib.
    """
    if TEXT_MODEL is None:
        raise RuntimeError(MODEL_LOAD_ERROR or "Text model is not loaded.")

    cleaned_text = str(text).strip()

    if not cleaned_text:
        raise ValueError("No text was provided.")

    prediction = str(TEXT_MODEL.predict([cleaned_text])[0])

    scores: dict[str, float] = {}

    if hasattr(TEXT_MODEL, "predict_proba"):
        probabilities = TEXT_MODEL.predict_proba([cleaned_text])[0]
        model_classes = get_model_classes(TEXT_MODEL)

        for class_name, probability in zip(model_classes, probabilities):
            scores[str(class_name)] = float(probability)

    else:
        scores = {
            label: 1.0 if label == prediction else 0.0
            for label in BEHAVIOUR_CLASSES
        }

    behaviour_scores = normalise_scores(scores)

    if prediction not in behaviour_scores:
        prediction = get_best_label(behaviour_scores)

    confidence = behaviour_scores.get(prediction, 0.0)

    return {
        "input_text": cleaned_text,
        "predicted_behaviour": prediction,
        "confidence": float(confidence),
        "behaviour_scores": behaviour_scores,
        "model_path": str(MODEL_PATH),
        "metadata_path": str(META_PATH),
        "model_name": TEXT_META.get("model_name", "text_model.joblib"),
        "method": TEXT_META.get("method", "unknown"),
        "selected_classifier": TEXT_META.get("selected_classifier"),
        "selection_metric": TEXT_META.get("selection_metric"),
        "training_accuracy": TEXT_META.get("accuracy"),
        "training_macro_f1": TEXT_META.get("macro_f1"),
        "training_weighted_f1": TEXT_META.get("weighted_f1"),
        "classes": TEXT_META.get("classes", BEHAVIOUR_CLASSES),
    }


def analyse_live_text(text: str) -> dict[str, Any]:
    """
    Run both behavioural prediction and sentiment estimation.
    """
    behaviour_result = predict_text_behaviour(text)
    sentiment_result = predict_text_sentiment(text)

    return {
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "modality": "text",
        **behaviour_result,
        "sentiment": sentiment_result,
        "methodological_note": (
            "The behavioural state is predicted using the trained text_model.joblib "
            "pipeline created by train_text_model.py. The model accepts raw live "
            "text input and returns one of the four SenseFuzeAI behavioural states. "
            "Sentiment is estimated separately using lightweight lexical scoring "
            "and should be interpreted as supporting evidence rather than the "
            "primary behavioural classifier."
        ),
    }


# ============================================================
# Presentation interpretation
# ============================================================

def build_brief_interpretation(result: dict[str, Any]) -> str:
    """
    Build concise, demo-friendly interpretation text.
    """
    prediction = str(result.get("predicted_behaviour", "unknown"))
    sentiment = result.get("sentiment", {})
    input_text = str(result.get("input_text", "")).lower()

    sentiment_label = sentiment.get("sentiment_label", "neutral")

    if prediction == "focused":
        return (
            "The system classifies the text as focused because the wording is most "
            "consistent with concentration, task engagement, or stable progress."
        )

    if prediction == "distracted":
        if any(term in input_text for term in ["phone", "tabs", "scrolling", "messages", "multitasking"]):
            return (
                "The system classifies the text as distracted because the wording "
                "suggests attention switching, device checking, or competing tasks."
            )

        return (
            "The system classifies the text as distracted because the semantic cues "
            "suggest reduced attention or difficulty staying on task."
        )

    if prediction == "fatigued":
        if any(term in input_text for term in ["tired", "sleepy", "drained", "exhausted", "slow"]):
            return (
                "The system classifies the text as fatigued because the wording "
                "contains cues of tiredness, low energy, or reduced alertness."
            )

        return (
            "The system classifies the text as fatigued because the semantic pattern "
            "is most consistent with low energy or reduced cognitive stamina."
        )

    if prediction == "overloaded":
        if any(term in input_text for term in ["deadline", "deadlines", "overwhelmed", "too much", "pressure", "stress"]):
            return (
                "The system classifies the text as overloaded because the wording "
                "suggests high workload, pressure, deadlines, or cognitive strain."
            )

        return (
            "The system classifies the text as overloaded because the semantic cues "
            "suggest excessive task demand or pressure."
        )

    return (
        "The system could not identify a strong text-based behavioural cue. "
        "The result should be interpreted as supporting evidence."
    )


def build_summary_text(result: dict[str, Any]) -> str:
    """
    Build presentation-friendly output.
    """
    prediction = str(result.get("predicted_behaviour", "unknown"))
    confidence = float(result.get("confidence", 0.0))
    scores = normalise_scores(result.get("behaviour_scores", {}))
    sentiment = result.get("sentiment", {})
    interpretation = result.get("brief_interpretation", "")

    sentiment_label = sentiment.get("sentiment_label", "unknown")
    sentiment_score = float(sentiment.get("sentiment_score", 0.0))

    display_prediction = prediction.upper()

    lines = [
        "SenseFuzeAI Live Text Behaviour Test",
        "=" * 50,
        "",
        f"Final Prediction: {display_prediction}",
        f"Confidence: {format_percent(confidence)}",
        f"Sentiment: {sentiment_label} ({format_percent(sentiment_score)})",
        "",
        "Final Behaviour Probabilities",
        "-" * 50,
        format_scores_percent(scores),
        "",
        "Brief Interpretation",
        "-" * 50,
        interpretation,
        "",
        "Text Evidence",
        "-" * 50,
        f"Input length: {len(str(result.get('input_text', '')))} characters",
        f"Sentiment method: {sentiment.get('method', 'unknown')}",
        f"Positive lexical hits: {sentiment.get('positive_count', 0)}",
        f"Negative lexical hits: {sentiment.get('negative_count', 0)}",
        "",
        "Technical Details",
        "-" * 50,
        "Full model metadata, class probabilities, sentiment lexical hits,",
        "and diagnostic information are available through the",
        "'Show Technical Details' button and export functions.",
        "",
        "Report Export",
        "-" * 50,
        "Full result available as JSON, CSV, or TXT report.",
    ]

    return "\n".join(lines)


def build_technical_text(result: dict[str, Any]) -> str:
    """
    Build full technical diagnostic output.
    """
    scores = normalise_scores(result.get("behaviour_scores", {}))
    sentiment = result.get("sentiment", {})

    lines = [
        "SenseFuzeAI Live Text Test - Technical Details",
        "=" * 70,
        "",
        f"Created at:              {result.get('created_at')}",
        f"Modality:                {result.get('modality')}",
        f"Predicted behaviour:     {result.get('predicted_behaviour')}",
        f"Confidence:              {float(result.get('confidence', 0.0)):.4f}",
        "",
        "Input text:",
        str(result.get("input_text", "")),
        "",
        "Behaviour class probabilities:",
        format_scores_decimal(scores),
        "",
        "Sentiment estimation:",
        f"  Sentiment label:       {sentiment.get('sentiment_label')}",
        f"  Sentiment score:       {float(sentiment.get('sentiment_score', 0.0)):.4f}",
        f"  Positive hits:         {sentiment.get('positive_count')}",
        f"  Negative hits:         {sentiment.get('negative_count')}",
        f"  Sentiment method:      {sentiment.get('method')}",
    ]

    positive_hits = sentiment.get("positive_hits", [])
    negative_hits = sentiment.get("negative_hits", [])

    if positive_hits:
        lines.append(f"  Positive words:        {', '.join(positive_hits)}")

    if negative_hits:
        lines.append(f"  Negative words:        {', '.join(negative_hits)}")

    lines.extend(
        [
            "",
            "Model information:",
            f"  Model name:            {result.get('model_name')}",
            f"  Method:                {result.get('method')}",
            f"  Selected classifier:   {result.get('selected_classifier')}",
            f"  Selection metric:      {result.get('selection_metric')}",
            f"  Model path:            {result.get('model_path')}",
            f"  Metadata path:         {result.get('metadata_path')}",
        ]
    )

    if result.get("training_accuracy") is not None:
        lines.append(
            f"  Training accuracy:     {float(result.get('training_accuracy')):.4f}"
        )

    if result.get("training_macro_f1") is not None:
        lines.append(
            f"  Training macro F1:     {float(result.get('training_macro_f1')):.4f}"
        )

    if result.get("training_weighted_f1") is not None:
        lines.append(
            f"  Training weighted F1:  {float(result.get('training_weighted_f1')):.4f}"
        )

    lines.extend(
        [
            "",
            "Full diagnostic JSON:",
            json.dumps(result, indent=2, default=str),
            "",
            "Methodological note:",
            str(result.get("methodological_note", "")),
        ]
    )

    return "\n".join(lines)


# ============================================================
# GUI actions
# ============================================================

def run_text_prediction() -> None:
    """
    Run live text behaviour and sentiment prediction.
    """
    global latest_text_result
    global latest_summary_text
    global latest_technical_text

    typed_text = input_box.get("1.0", tk.END).strip()

    output_box.delete("1.0", tk.END)

    if not typed_text:
        latest_text_result = None
        latest_summary_text = ""
        latest_technical_text = ""
        output_box.insert(tk.END, "Please enter some text.\n")
        return

    try:
        output_box.insert(
            tk.END,
            "Analysing text using trained text_model.joblib and sentiment scoring...\n\n",
        )
        root.update_idletasks()

        result = analyse_live_text(typed_text)
        result["brief_interpretation"] = build_brief_interpretation(result)

        latest_text_result = result
        latest_summary_text = build_summary_text(result)
        latest_technical_text = build_technical_text(result)

        output_box.delete("1.0", tk.END)
        output_box.insert(tk.END, latest_summary_text)

    except Exception as error:
        latest_text_result = None
        latest_summary_text = ""
        latest_technical_text = ""

        output_box.delete("1.0", tk.END)
        output_box.insert(tk.END, "Text model prediction failed.\n\n")
        output_box.insert(tk.END, str(error))


def show_technical_details() -> None:
    """
    Open a separate window showing detailed diagnostic output.
    """
    result = require_latest_result()

    if result is None:
        return

    details_window = tk.Toplevel(root)
    details_window.title("Text Technical Details")
    details_window.geometry("1020x780")

    title = tk.Label(
        details_window,
        text="Text Technical Details",
        font=("Arial", 16, "bold"),
    )
    title.pack(pady=10)

    details_box = scrolledtext.ScrolledText(
        details_window,
        width=120,
        height=40,
        font=("Consolas", 10),
    )
    details_box.pack(padx=12, pady=10, fill=tk.BOTH, expand=True)

    details_box.insert(tk.END, latest_technical_text)
    details_box.configure(state="disabled")

    close_button = tk.Button(
        details_window,
        text="Close",
        command=details_window.destroy,
        width=16,
    )
    close_button.pack(pady=8)


def reset_session() -> None:
    """
    Reset GUI state.
    """
    global latest_text_result
    global latest_summary_text
    global latest_technical_text

    latest_text_result = None
    latest_summary_text = ""
    latest_technical_text = ""

    input_box.delete("1.0", tk.END)
    output_box.delete("1.0", tk.END)
    output_box.insert(tk.END, "Session reset. Enter text to begin analysis.\n")


def show_guidance() -> None:
    """
    Show text test guidance.
    """
    messagebox.showinfo(
        "Text Test Guidance",
        "Example inputs:\n\n"
        "Focused:\n"
        "I am calm, focused, and making steady progress on my work.\n\n"
        "Distracted:\n"
        "I keep checking my phone and switching tabs instead of working.\n\n"
        "Fatigued:\n"
        "I feel tired, slow, and mentally drained after working for a long time.\n\n"
        "Overloaded:\n"
        "I am overwhelmed by too many deadlines and too much information.\n\n"
        "The main screen shows a concise demo-friendly result. "
        "Use 'Show Technical Details' to inspect the model output and sentiment evidence.",
    )


def show_model_status() -> None:
    """
    Show loaded text model status.
    """
    if MODEL_LOAD_ERROR:
        messagebox.showerror(
            "Model Status",
            MODEL_LOAD_ERROR,
        )
        return

    message = (
        "Text model loaded successfully.\n\n"
        f"Model path:\n{MODEL_PATH}\n\n"
        f"Metadata path:\n{META_PATH}\n\n"
        f"Model name: {TEXT_META.get('model_name', 'unknown')}\n"
        f"Method: {TEXT_META.get('method', 'unknown')}\n"
    )

    if TEXT_META.get("selected_classifier") is not None:
        message += f"Selected classifier: {TEXT_META.get('selected_classifier')}\n"

    if TEXT_META.get("selection_metric") is not None:
        message += f"Selection metric: {TEXT_META.get('selection_metric')}\n"

    if TEXT_META.get("accuracy") is not None:
        message += f"Accuracy: {float(TEXT_META['accuracy']):.4f}\n"

    if TEXT_META.get("macro_f1") is not None:
        message += f"Macro F1: {float(TEXT_META['macro_f1']):.4f}\n"

    if TEXT_META.get("weighted_f1") is not None:
        message += f"Weighted F1: {float(TEXT_META['weighted_f1']):.4f}\n"

    message += (
        "\nSentiment estimation is performed separately using "
        "rule-based lexical scoring."
    )

    messagebox.showinfo("Model Status", message)


def show_export_guidance() -> None:
    """
    Explain export functionality.
    """
    messagebox.showinfo(
        "Export Guidance",
        "After running a text prediction, you can export the latest result as:\n\n"
        "1. JSON: full diagnostic result, summary, and technical report\n"
        "2. CSV: compact one-row summary for spreadsheet analysis\n"
        "3. TXT: readable report containing both the presentation summary and technical details\n\n"
        f"Exports are saved in:\n{EXPORT_DIR}",
    )


# ============================================================
# Export functions
# ============================================================

def export_latest_result_json() -> None:
    """
    Export latest text result as JSON.
    """
    result = require_latest_result()

    if result is None:
        return

    output_path = EXPORT_DIR / f"text_result_{timestamp_for_filename()}.json"

    export_payload = {
        **result,
        "presentation_summary": latest_summary_text,
        "technical_report": latest_technical_text,
    }

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(export_payload, f, indent=4, default=str)

    messagebox.showinfo(
        "Export Complete",
        f"JSON result exported successfully:\n\n{output_path}",
    )


def export_latest_result_csv() -> None:
    """
    Export latest text result as one-row CSV summary.
    """
    result = require_latest_result()

    if result is None:
        return

    output_path = EXPORT_DIR / f"text_result_{timestamp_for_filename()}.csv"

    sentiment = result.get("sentiment", {})
    behaviour_scores = normalise_scores(result.get("behaviour_scores", {}))

    row: dict[str, Any] = {
        "created_at": result.get("created_at"),
        "modality": result.get("modality"),
        "input_text": result.get("input_text"),
        "predicted_behaviour": result.get("predicted_behaviour"),
        "behaviour_confidence": result.get("confidence"),
        "behaviour_confidence_percent": format_percent(float(result.get("confidence", 0.0))),
        "brief_interpretation": result.get("brief_interpretation"),
        "sentiment_label": sentiment.get("sentiment_label"),
        "sentiment_score": sentiment.get("sentiment_score"),
        "sentiment_score_percent": format_percent(float(sentiment.get("sentiment_score", 0.0))),
        "positive_count": sentiment.get("positive_count"),
        "negative_count": sentiment.get("negative_count"),
        "positive_hits": ", ".join(sentiment.get("positive_hits", [])),
        "negative_hits": ", ".join(sentiment.get("negative_hits", [])),
        "sentiment_method": sentiment.get("method"),
        "model_name": result.get("model_name"),
        "method": result.get("method"),
        "selected_classifier": result.get("selected_classifier"),
        "selection_metric": result.get("selection_metric"),
        "training_accuracy": result.get("training_accuracy"),
        "training_macro_f1": result.get("training_macro_f1"),
        "training_weighted_f1": result.get("training_weighted_f1"),
        "model_path": result.get("model_path"),
        "metadata_path": result.get("metadata_path"),
    }

    for label in BEHAVIOUR_CLASSES:
        row[f"prob_{label}"] = behaviour_scores.get(label, 0.0)

    with open(output_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(row.keys()))
        writer.writeheader()
        writer.writerow(row)

    messagebox.showinfo(
        "Export Complete",
        f"CSV summary exported successfully:\n\n{output_path}",
    )


def export_latest_result_txt() -> None:
    """
    Export latest text result as a human-readable TXT report.
    """
    result = require_latest_result()

    if result is None:
        return

    output_path = EXPORT_DIR / f"text_report_{timestamp_for_filename()}.txt"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("SenseFuzeAI Live Text Behaviour Test Report\n")
        f.write("===========================================\n\n")

        f.write("Presentation Summary\n")
        f.write("--------------------\n")
        f.write(latest_summary_text)
        f.write("\n\n")

        f.write("Technical Diagnostic Details\n")
        f.write("----------------------------\n")
        f.write(latest_technical_text)
        f.write("\n")

    messagebox.showinfo(
        "Export Complete",
        f"Text report exported successfully:\n\n{output_path}",
    )


# ============================================================
# GUI construction
# ============================================================

root = tk.Tk()
root.title("SenseFuzeAI Live Text Behaviour Test")
root.geometry("1040x860")

title_label = tk.Label(
    root,
    text="SenseFuzeAI Live Text Behaviour Test",
    font=("Arial", 18, "bold"),
)
title_label.pack(pady=10)

if MODEL_LOAD_ERROR:
    status_text = (
        "Model status: text_model.joblib not loaded. "
        "Run python train_text_model.py first."
    )
    status_colour = "red"
else:
    status_text = (
        "Model status: text_model.joblib loaded successfully. "
        "Enter text to classify behavioural state and estimate sentiment."
    )
    status_colour = "green"

status_label = tk.Label(
    root,
    text=status_text,
    font=("Arial", 10, "bold"),
    fg=status_colour,
    wraplength=960,
)
status_label.pack(pady=5)

instruction_label = tk.Label(
    root,
    text=(
        "Enter live text below. The main result is simplified for prototype "
        "demonstration, while full technical diagnostics remain available separately."
    ),
    font=("Arial", 11),
    wraplength=960,
)
instruction_label.pack(pady=5)

input_box = scrolledtext.ScrolledText(
    root,
    width=122,
    height=10,
    font=("Consolas", 10),
)
input_box.pack(padx=15, pady=10)

button_frame = tk.Frame(root)
button_frame.pack(pady=8)

predict_button = tk.Button(
    button_frame,
    text="Predict Behaviour + Sentiment",
    command=run_text_prediction,
    width=30,
)
predict_button.grid(row=0, column=0, padx=6, pady=4)

technical_button = tk.Button(
    button_frame,
    text="Show Technical Details",
    command=show_technical_details,
    width=24,
)
technical_button.grid(row=0, column=1, padx=6, pady=4)

reset_button = tk.Button(
    button_frame,
    text="Reset",
    command=reset_session,
    width=14,
)
reset_button.grid(row=0, column=2, padx=6, pady=4)

help_button = tk.Button(
    button_frame,
    text="Guidance",
    command=show_guidance,
    width=14,
)
help_button.grid(row=0, column=3, padx=6, pady=4)

status_button = tk.Button(
    button_frame,
    text="Model Status",
    command=show_model_status,
    width=16,
)
status_button.grid(row=0, column=4, padx=6, pady=4)

export_frame = tk.Frame(root)
export_frame.pack(pady=5)

export_json_button = tk.Button(
    export_frame,
    text="Export JSON",
    command=export_latest_result_json,
    width=18,
)
export_json_button.grid(row=0, column=0, padx=6, pady=4)

export_csv_button = tk.Button(
    export_frame,
    text="Export CSV",
    command=export_latest_result_csv,
    width=18,
)
export_csv_button.grid(row=0, column=1, padx=6, pady=4)

export_txt_button = tk.Button(
    export_frame,
    text="Export Report",
    command=export_latest_result_txt,
    width=18,
)
export_txt_button.grid(row=0, column=2, padx=6, pady=4)

export_help_button = tk.Button(
    export_frame,
    text="Export Help",
    command=show_export_guidance,
    width=18,
)
export_help_button.grid(row=0, column=3, padx=6, pady=4)

output_box = scrolledtext.ScrolledText(
    root,
    width=122,
    height=25,
    font=("Consolas", 10),
)
output_box.pack(padx=15, pady=15)

if MODEL_LOAD_ERROR:
    output_box.insert(
        tk.END,
        "Text model is not available.\n\n"
        "To fix this:\n"
        "1. Ensure data/processed/processed_text_dataset.csv exists.\n"
        "2. Run: python train_text_model.py\n"
        "3. Confirm model_artifacts/text_model.joblib is created.\n"
        "4. Re-run this live text test script.\n",
    )
else:
    output_box.insert(
        tk.END,
        "Waiting for text input...\n\n"
        "Steps:\n"
        "1. Type a sentence or paragraph.\n"
        "2. Click 'Predict Behaviour + Sentiment'.\n"
        "3. The main output will show a concise result suitable for video demonstration.\n"
        "4. Click 'Show Technical Details' to inspect model metadata, class probabilities, and sentiment evidence.\n"
        "5. Export the latest result as JSON, CSV, or TXT report if needed.\n\n"
        f"Export directory:\n{EXPORT_DIR}\n",
    )

root.mainloop()
